// This file is auto-generated by @hey-api/openapi-ts

export const CompanyCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const CompanyDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const CompanyInfoSchema = {
    type: 'object',
    required: [
        'id',
        'title',
        'guimo',
        'hangye',
        'description',
        'location'
    ],
    properties: {
        description: {
            type: 'string'
        },
        guimo: {
            type: 'string'
        },
        hangye: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        title: {
            type: 'string'
        }
    }
} as const;

export const CompanyListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/CompanyInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const CompanyListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/CompanyListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const CompanyUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const DepartmentCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const DepartmentDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const DepartmentInfoSchema = {
    type: 'object',
    required: [
        'id',
        'title',
        'description',
        'parentId',
        'createTime'
    ],
    properties: {
        createTime: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        parentId: {
            type: 'string'
        },
        title: {
            type: 'string'
        }
    }
} as const;

export const DepartmentListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/DepartmentInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const DepartmentListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/DepartmentListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const DepartmentUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const InterviewCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const InterviewInfoSchema = {
    type: 'object',
    required: [
        'id',
        'postId',
        'round',
        'interviewerId',
        'interviewerName',
        'scheduledAt',
        'location',
        'type',
        'result',
        'score',
        'evaluation',
        'createTime'
    ],
    properties: {
        createTime: {
            type: 'string'
        },
        evaluation: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        interviewerId: {
            type: 'string'
        },
        interviewerName: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        result: {
            type: 'string'
        },
        round: {
            type: 'string'
        },
        scheduledAt: {
            type: 'string'
        },
        score: {
            type: 'string'
        },
        type: {
            type: 'string'
        }
    }
} as const;

export const InterviewListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/InterviewInfo'
            }
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const InterviewUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const JobCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const JobDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const JobInfoSchema = {
    type: 'object',
    required: [
        'id',
        'jobCode',
        'title',
        'description',
        'requirement',
        'education',
        'status',
        'createTime',
        'updateTime',
        'location',
        'address',
        'minSalary',
        'maxSalary',
        'salaryUnit',
        'salaryShow',
        'workExpe',
        'pv',
        'category',
        'recruitType',
        'jobNature',
        'departmentId',
        'departmentTitle',
        'companyId',
        'companyTitle'
    ],
    properties: {
        address: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        companyId: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        departmentId: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        jobCode: {
            type: 'string'
        },
        jobNature: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        maxSalary: {
            type: 'integer'
        },
        minSalary: {
            type: 'integer'
        },
        pv: {
            type: 'integer'
        },
        recruitType: {
            type: 'string'
        },
        requirement: {
            type: 'string'
        },
        salaryShow: {
            type: 'string'
        },
        salaryUnit: {
            type: 'integer'
        },
        status: {
            type: 'integer'
        },
        title: {
            type: 'string'
        },
        updateTime: {
            type: 'string'
        },
        workExpe: {
            type: 'string'
        }
    }
} as const;

export const JobDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/JobInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const JobListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/JobInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const JobListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/JobListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const JobUserListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/JobListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const JobUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const OfferCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const OfferDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const OfferInfoSchema = {
    type: 'object',
    required: [
        'id',
        'postId',
        'salary',
        'level',
        'joinDate',
        'contractPeriod',
        'probationPeriod',
        'workLocation',
        'status',
        'createTime'
    ],
    properties: {
        contractPeriod: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        joinDate: {
            type: 'string'
        },
        level: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        probationPeriod: {
            type: 'string'
        },
        salary: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        workLocation: {
            type: 'string'
        }
    }
} as const;

export const OfferDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OfferInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const OfferListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/OfferInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const OfferListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OfferListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const OfferUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const OpLogInfoSchema = {
    type: 'object',
    required: [
        'id',
        'requestId',
        'reIp',
        'reTime',
        'reUa',
        'reUrl',
        'reMethod',
        'reContent',
        'success',
        'bizCode',
        'bizMsg',
        'accessTime'
    ],
    properties: {
        accessTime: {
            type: 'string'
        },
        bizCode: {
            type: 'integer'
        },
        bizMsg: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        reContent: {
            type: 'string'
        },
        reIp: {
            type: 'string'
        },
        reMethod: {
            type: 'string'
        },
        reTime: {
            type: 'string'
        },
        reUa: {
            type: 'string'
        },
        reUrl: {
            type: 'string'
        },
        requestId: {
            type: 'string'
        },
        success: {
            type: 'string'
        }
    }
} as const;

export const OpLogListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/OpLogInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const OpLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OpLogListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const LoginLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OpLogListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const PostCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const PostCreateFromSnapshotRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const PostDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const PostInfoSchema = {
    type: 'object',
    required: [
        'id',
        'title',
        'companyTitle',
        'name',
        'resumeSnapshotId',
        'raw',
        'jobId',
        'companyId',
        'status',
        'feedback',
        'remark',
        'source',
        'userId',
        'createTime'
    ],
    properties: {
        companyId: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        feedback: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        resumeSnapshotId: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const PostListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/PostInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const PostListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/PostListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const PostCompanyListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/PostListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserPostItemInfoSchema = {
    type: 'object',
    required: [
        'id',
        'jobId',
        'title',
        'status',
        'feedback',
        'source',
        'companyTitle',
        'location',
        'categoryTitle',
        'departmentTitle'
    ],
    properties: {
        categoryTitle: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        },
        feedback: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        title: {
            type: 'string'
        }
    }
} as const;

export const UserPostListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/UserPostItemInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const PostUserListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserPostListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const StatusLogInfoSchema = {
    type: 'object',
    required: [
        'id',
        'targetType',
        'targetId',
        'fromStatus',
        'toStatus',
        'feedback',
        'remark',
        'operatorId',
        'operatorName',
        'createTime'
    ],
    properties: {
        createTime: {
            type: 'integer'
        },
        feedback: {
            type: 'string'
        },
        fromStatus: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        operatorId: {
            type: 'string'
        },
        operatorName: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        targetId: {
            type: 'string'
        },
        targetType: {
            type: 'string'
        },
        toStatus: {
            type: 'string'
        }
    }
} as const;

export const PostStatusLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/StatusLogInfo'
            }
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const PostUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const InterviewWithJobInfoSchema = {
    type: 'object',
    required: [
        'id',
        'postId',
        'round',
        'interviewerId',
        'interviewerName',
        'scheduledAt',
        'location',
        'type',
        'result',
        'score',
        'evaluation',
        'createTime',
        'jobId',
        'jobTitle',
        'companyTitle',
        'jobLocation',
        'categoryTitle',
        'departmentTitle',
        'postStatus'
    ],
    properties: {
        categoryTitle: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        },
        evaluation: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        interviewerId: {
            type: 'string'
        },
        interviewerName: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        jobLocation: {
            type: 'string'
        },
        jobTitle: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        postStatus: {
            type: 'string'
        },
        result: {
            type: 'string'
        },
        round: {
            type: 'string'
        },
        scheduledAt: {
            type: 'string'
        },
        score: {
            type: 'string'
        },
        type: {
            type: 'string'
        }
    }
} as const;

export const PostUserInterviewListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/InterviewWithJobInfo'
            }
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const OfferWithJobInfoSchema = {
    type: 'object',
    required: [
        'id',
        'postId',
        'salary',
        'level',
        'joinDate',
        'contractPeriod',
        'probationPeriod',
        'workLocation',
        'status',
        'createTime',
        'jobId',
        'jobTitle',
        'companyTitle',
        'jobLocation',
        'categoryTitle',
        'departmentTitle',
        'postStatus'
    ],
    properties: {
        categoryTitle: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        contractPeriod: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        jobLocation: {
            type: 'string'
        },
        jobTitle: {
            type: 'string'
        },
        joinDate: {
            type: 'string'
        },
        level: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        postStatus: {
            type: 'string'
        },
        probationPeriod: {
            type: 'string'
        },
        salary: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        workLocation: {
            type: 'string'
        }
    }
} as const;

export const PostUserOfferListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/OfferWithJobInfo'
            }
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const TaskIdDataSchema = {
    type: 'object',
    required: [
        'taskId'
    ],
    properties: {
        taskId: {
            type: 'string'
        }
    }
} as const;

export const ResumeCompanyUploadRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/TaskIdData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeInfoSchema = {
    type: 'object',
    required: [
        'id',
        'cover',
        'name',
        'sex',
        'birthday',
        'raw',
        'education',
        'school',
        'email',
        'mobile',
        'summary',
        'skills',
        'experience',
        'projects',
        'eduDetail',
        'expectedSalary',
        'jobIntention',
        'source',
        'createTime',
        'userId'
    ],
    properties: {
        birthday: {
            type: 'string'
        },
        cover: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const ResumeDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/ResumeInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const ResumeListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeParseRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/TaskIdData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ParseTaskMetaSchema = {
    type: 'object',
    required: [
        'fileName',
        'textLength',
        'llmStatus',
        'llmError',
        'strategy',
        'startedAt',
        'finishedAt',
        'extractError'
    ],
    properties: {
        extractError: {
            type: 'string'
        },
        fileName: {
            type: 'string'
        },
        finishedAt: {
            type: 'string'
        },
        llmError: {
            type: 'string'
        },
        llmStatus: {
            type: 'string'
        },
        startedAt: {
            type: 'string'
        },
        strategy: {
            type: 'string'
        },
        textLength: {
            type: 'integer'
        }
    }
} as const;

export const interface__Schema = {} as const;

export const ParseTaskInfoSchema = {
    type: 'object',
    required: [
        'status',
        'result',
        'msg',
        'meta'
    ],
    properties: {
        meta: {
            $ref: '#/definitions/ParseTaskMeta'
        },
        msg: {
            type: 'string'
        },
        result: {
            $ref: '#/definitions/interface{}'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const ResumeParseResultRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ParseTaskInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeSnapshotDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeSnapshotInfoSchema = {
    type: 'object',
    required: [
        'id',
        'userId',
        'resumeId',
        'name',
        'sex',
        'birthday',
        'cover',
        'email',
        'mobile',
        'education',
        'school',
        'skills',
        'experience',
        'projects',
        'summary',
        'eduDetail',
        'expectedSalary',
        'jobIntention',
        'raw',
        'rating',
        'tags',
        'remark',
        'source',
        'createTime'
    ],
    properties: {
        birthday: {
            type: 'string'
        },
        cover: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        rating: {
            type: 'integer'
        },
        raw: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        resumeId: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        tags: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    }
} as const;

export const ResumeSnapshotDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeSnapshotInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeSnapshotListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/ResumeSnapshotInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const ResumeSnapshotListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeSnapshotListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeSnapshotStatusLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/StatusLogInfo'
            }
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const ResumeSnapshotUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const TalentPoolAddRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const TalentPoolInfoSchema = {
    type: 'object',
    required: [
        'id',
        'resumeSnapshotId',
        'name',
        'email',
        'mobile',
        'education',
        'rating',
        'tags',
        'remark',
        'createTime'
    ],
    properties: {
        createTime: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        rating: {
            type: 'integer'
        },
        remark: {
            type: 'string'
        },
        resumeSnapshotId: {
            type: 'string'
        },
        tags: {
            type: 'string'
        }
    }
} as const;

export const TalentPoolListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/TalentPoolInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const TalentPoolListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/TalentPoolListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const TalentPoolRemoveRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const TalentPoolUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserInfoSchema = {
    type: 'object',
    required: [
        'id',
        'username',
        'password',
        'nickname',
        'mobile',
        'email',
        'role',
        'status',
        'token',
        'createTime',
        'pushEmail',
        'pushSwitch',
        'avatar'
    ],
    properties: {
        avatar: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        nickname: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        pushEmail: {
            type: 'string'
        },
        pushSwitch: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        token: {
            type: 'string'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const UserDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserListDataSchema = {
    type: 'object',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ],
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/UserInfo'
            }
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const UserListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserListData'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserLoginRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserUpdatePwdRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserUpdateUserInfoRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserLoginResp2Schema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserInfo'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;

export const UserRegisterRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        trace: {
            type: 'string'
        }
    }
} as const;
