// This file is auto-generated by @hey-api/openapi-ts

export const BaseRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'BaseResp',
    required: [
        'code',
        'msg',
        'timestamp'
    ]
} as const;

export const CategoryListDataSchema = {
    type: 'object',
    properties: {
        categories: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    title: 'CategoryListData',
    required: [
        'categories'
    ]
} as const;

export const CompanyCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'CompanyCreateResp'
} as const;

export const CompanyDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'CompanyDeleteResp'
} as const;

export const CompanyInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        guimo: {
            type: 'string'
        },
        hangye: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        location: {
            type: 'string'
        }
    },
    title: 'CompanyInfo',
    required: [
        'id',
        'title',
        'guimo',
        'hangye',
        'description',
        'location'
    ]
} as const;

export const CompanyListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/CompanyInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'CompanyListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const CompanyListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'CompanyListReq'
} as const;

export const CompanyListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/CompanyListData'
        }
    },
    title: 'CompanyListResp'
} as const;

export const CompanyUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'CompanyUpdateResp'
} as const;

export const CompanyUploadResumeReqSchema = {
    type: 'object',
    properties: {
        rawFile: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        addToTalentPool: {
            type: 'string'
        }
    },
    title: 'CompanyUploadResumeReq'
} as const;

export const CreateCompanyReqSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        guimo: {
            type: 'string'
        },
        hangye: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        location: {
            type: 'string'
        }
    },
    title: 'CreateCompanyReq',
    required: [
        'title'
    ]
} as const;

export const CreateDepartmentReqSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        parentId: {
            type: 'string'
        }
    },
    title: 'CreateDepartmentReq',
    required: [
        'title'
    ]
} as const;

export const CreateInterviewReqSchema = {
    type: 'object',
    properties: {
        postId: {
            type: 'string'
        },
        round: {
            type: 'string'
        },
        interviewerId: {
            type: 'string'
        },
        interviewerName: {
            type: 'string'
        },
        scheduledAt: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        result: {
            type: 'string'
        },
        score: {
            type: 'string'
        },
        evaluation: {
            type: 'string'
        }
    },
    title: 'CreateInterviewReq',
    required: [
        'postId',
        'round'
    ]
} as const;

export const CreateJobReqSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        jobCode: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        requirement: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        status: {
            type: 'integer'
        },
        location: {
            type: 'string'
        },
        address: {
            type: 'string'
        },
        minSalary: {
            type: 'integer'
        },
        maxSalary: {
            type: 'integer'
        },
        salaryUnit: {
            type: 'integer'
        },
        salaryShow: {
            type: 'string'
        },
        workExpe: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        recruitType: {
            type: 'string'
        },
        jobNature: {
            type: 'string'
        },
        departmentId: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        companyId: {
            type: 'string'
        }
    },
    title: 'CreateJobReq',
    required: [
        'title'
    ]
} as const;

export const CreateOfferReqSchema = {
    type: 'object',
    properties: {
        postId: {
            type: 'string'
        },
        salary: {
            type: 'string'
        },
        level: {
            type: 'string'
        },
        joinDate: {
            type: 'string'
        },
        contractPeriod: {
            type: 'string'
        },
        probationPeriod: {
            type: 'string'
        },
        workLocation: {
            type: 'string'
        }
    },
    title: 'CreateOfferReq',
    required: [
        'postId'
    ]
} as const;

export const CreatePostFromSnapshotReqSchema = {
    type: 'object',
    properties: {
        resumeSnapshotId: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        }
    },
    title: 'CreatePostFromSnapshotReq',
    required: [
        'resumeSnapshotId',
        'jobId'
    ]
} as const;

export const CreatePostReqSchema = {
    type: 'object',
    properties: {
        resumeId: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        companyId: {
            type: 'string'
        },
        source: {
            type: 'string'
        }
    },
    title: 'CreatePostReq',
    required: [
        'userId'
    ]
} as const;

export const CreateResumeReqSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        birthday: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        coverFile: {
            type: 'string'
        },
        rawFile: {
            type: 'string'
        }
    },
    title: 'CreateResumeReq',
    required: [
        'name',
        'userId'
    ]
} as const;

export const CreateUserReqSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        nickname: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    },
    title: 'CreateUserReq',
    required: [
        'username',
        'password'
    ]
} as const;

export const DeleteReqSchema = {
    type: 'object',
    properties: {
        ids: {
            type: 'string'
        }
    },
    title: 'DeleteReq',
    required: [
        'ids'
    ]
} as const;

export const DepartmentCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'DepartmentCreateResp'
} as const;

export const DepartmentDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'DepartmentDeleteResp'
} as const;

export const DepartmentInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        parentId: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        }
    },
    title: 'DepartmentInfo',
    required: [
        'id',
        'title',
        'description',
        'parentId',
        'createTime'
    ]
} as const;

export const DepartmentListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/DepartmentInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'DepartmentListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const DepartmentListReqSchema = {
    type: 'object',
    properties: {
        keyword: {
            type: 'string'
        },
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'DepartmentListReq'
} as const;

export const DepartmentListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/DepartmentListData'
        }
    },
    title: 'DepartmentListResp'
} as const;

export const DepartmentUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'DepartmentUpdateResp'
} as const;

export const InterviewCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'InterviewCreateResp'
} as const;

export const InterviewInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        round: {
            type: 'string'
        },
        interviewerId: {
            type: 'string'
        },
        interviewerName: {
            type: 'string'
        },
        scheduledAt: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        result: {
            type: 'string'
        },
        score: {
            type: 'string'
        },
        evaluation: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        }
    },
    title: 'InterviewInfo',
    required: [
        'id',
        'postId',
        'round',
        'interviewerId',
        'interviewerName',
        'scheduledAt',
        'location',
        'type',
        'result',
        'score',
        'evaluation',
        'createTime'
    ]
} as const;

export const InterviewListReqSchema = {
    type: 'object',
    properties: {
        postId: {
            type: 'string'
        }
    },
    title: 'InterviewListReq',
    required: [
        'postId'
    ]
} as const;

export const InterviewListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/InterviewInfo'
            }
        }
    },
    title: 'InterviewListResp'
} as const;

export const InterviewUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'InterviewUpdateResp'
} as const;

export const InterviewWithJobInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        round: {
            type: 'string'
        },
        interviewerId: {
            type: 'string'
        },
        interviewerName: {
            type: 'string'
        },
        scheduledAt: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        result: {
            type: 'string'
        },
        score: {
            type: 'string'
        },
        evaluation: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        jobTitle: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        jobLocation: {
            type: 'string'
        },
        categoryTitle: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        },
        postStatus: {
            type: 'string'
        }
    },
    title: 'InterviewWithJobInfo',
    required: [
        'id',
        'postId',
        'round',
        'interviewerId',
        'interviewerName',
        'scheduledAt',
        'location',
        'type',
        'result',
        'score',
        'evaluation',
        'createTime',
        'jobId',
        'jobTitle',
        'companyTitle',
        'jobLocation',
        'categoryTitle',
        'departmentTitle',
        'postStatus'
    ]
} as const;

export const JobCategoryListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/CategoryListData'
        }
    },
    title: 'JobCategoryListResp'
} as const;

export const JobCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'JobCreateResp'
} as const;

export const JobDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'JobDeleteResp'
} as const;

export const JobDetailReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    title: 'JobDetailReq',
    required: [
        'id'
    ]
} as const;

export const JobDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/JobInfo'
        }
    },
    title: 'JobDetailResp'
} as const;

export const JobInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        jobCode: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        requirement: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        status: {
            type: 'integer'
        },
        createTime: {
            type: 'string'
        },
        updateTime: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        address: {
            type: 'string'
        },
        minSalary: {
            type: 'integer'
        },
        maxSalary: {
            type: 'integer'
        },
        salaryUnit: {
            type: 'integer'
        },
        salaryShow: {
            type: 'string'
        },
        workExpe: {
            type: 'string'
        },
        pv: {
            type: 'integer'
        },
        category: {
            type: 'string'
        },
        recruitType: {
            type: 'string'
        },
        jobNature: {
            type: 'string'
        },
        departmentId: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        },
        companyId: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        }
    },
    title: 'JobInfo',
    required: [
        'id',
        'jobCode',
        'title',
        'description',
        'requirement',
        'education',
        'status',
        'createTime',
        'updateTime',
        'location',
        'address',
        'minSalary',
        'maxSalary',
        'salaryUnit',
        'salaryShow',
        'workExpe',
        'pv',
        'category',
        'recruitType',
        'jobNature',
        'departmentId',
        'departmentTitle',
        'companyId',
        'companyTitle'
    ]
} as const;

export const JobListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/JobInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'JobListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const JobListReqSchema = {
    type: 'object',
    properties: {
        keyword: {
            type: 'string'
        },
        sort: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        recruitType: {
            type: 'string'
        },
        jobNature: {
            type: 'string'
        },
        salaryMin: {
            type: 'integer'
        },
        salaryMax: {
            type: 'integer'
        },
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'JobListReq'
} as const;

export const JobListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/JobListData'
        }
    },
    title: 'JobListResp'
} as const;

export const JobUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'JobUpdateResp'
} as const;

export const JobUserListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        },
        keyword: {
            type: 'string'
        }
    },
    title: 'JobUserListReq'
} as const;

export const JobUserListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/JobListData'
        }
    },
    title: 'JobUserListResp'
} as const;

export const LoginLogListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'LoginLogListReq'
} as const;

export const LoginLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OpLogListData'
        }
    },
    title: 'LoginLogListResp'
} as const;

export const LoginReqSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    title: 'LoginReq',
    required: [
        'username',
        'password'
    ]
} as const;

export const OfferCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'OfferCreateResp'
} as const;

export const OfferDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'OfferDeleteResp'
} as const;

export const OfferDetailReqSchema = {
    type: 'object',
    properties: {
        postId: {
            type: 'string'
        }
    },
    title: 'OfferDetailReq',
    required: [
        'postId'
    ]
} as const;

export const OfferDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OfferInfo'
        }
    },
    title: 'OfferDetailResp'
} as const;

export const OfferInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        salary: {
            type: 'string'
        },
        level: {
            type: 'string'
        },
        joinDate: {
            type: 'string'
        },
        contractPeriod: {
            type: 'string'
        },
        probationPeriod: {
            type: 'string'
        },
        workLocation: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        }
    },
    title: 'OfferInfo',
    required: [
        'id',
        'postId',
        'salary',
        'level',
        'joinDate',
        'contractPeriod',
        'probationPeriod',
        'workLocation',
        'status',
        'createTime'
    ]
} as const;

export const OfferListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/OfferInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'OfferListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const OfferListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'OfferListReq'
} as const;

export const OfferListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OfferListData'
        }
    },
    title: 'OfferListResp'
} as const;

export const OfferUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'OfferUpdateResp'
} as const;

export const OfferWithJobInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        postId: {
            type: 'string'
        },
        salary: {
            type: 'string'
        },
        level: {
            type: 'string'
        },
        joinDate: {
            type: 'string'
        },
        contractPeriod: {
            type: 'string'
        },
        probationPeriod: {
            type: 'string'
        },
        workLocation: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        jobTitle: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        jobLocation: {
            type: 'string'
        },
        categoryTitle: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        },
        postStatus: {
            type: 'string'
        }
    },
    title: 'OfferWithJobInfo',
    required: [
        'id',
        'postId',
        'salary',
        'level',
        'joinDate',
        'contractPeriod',
        'probationPeriod',
        'workLocation',
        'status',
        'createTime',
        'jobId',
        'jobTitle',
        'companyTitle',
        'jobLocation',
        'categoryTitle',
        'departmentTitle',
        'postStatus'
    ]
} as const;

export const OpLogInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        requestId: {
            type: 'string'
        },
        reIp: {
            type: 'string'
        },
        reTime: {
            type: 'string'
        },
        reUa: {
            type: 'string'
        },
        reUrl: {
            type: 'string'
        },
        reMethod: {
            type: 'string'
        },
        reContent: {
            type: 'string'
        },
        success: {
            type: 'string'
        },
        bizCode: {
            type: 'integer'
        },
        bizMsg: {
            type: 'string'
        },
        accessTime: {
            type: 'string'
        }
    },
    title: 'OpLogInfo',
    required: [
        'id',
        'requestId',
        'reIp',
        'reTime',
        'reUa',
        'reUrl',
        'reMethod',
        'reContent',
        'success',
        'bizCode',
        'bizMsg',
        'accessTime'
    ]
} as const;

export const OpLogListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/OpLogInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'OpLogListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const OpLogListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'OpLogListReq'
} as const;

export const OpLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/OpLogListData'
        }
    },
    title: 'OpLogListResp'
} as const;

export const ParseResultReqSchema = {
    type: 'object',
    properties: {
        taskId: {
            type: 'string'
        }
    },
    title: 'ParseResultReq',
    required: [
        'taskId'
    ]
} as const;

export const ParseResumeReqSchema = {
    type: 'object',
    properties: {
        rawFile: {
            type: 'string'
        }
    },
    title: 'ParseResumeReq'
} as const;

export const ParseResumeResultSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        skills: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        info: {
            type: 'string'
        },
        rawText: {
            type: 'string'
        }
    },
    title: 'ParseResumeResult',
    required: [
        'name',
        'email',
        'mobile',
        'skills',
        'info',
        'rawText'
    ]
} as const;

export const ParseTaskInfoSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string'
        },
        result: {
            $ref: '#/definitions/ParseResumeResult'
        },
        msg: {
            type: 'string'
        },
        meta: {
            $ref: '#/definitions/ParseTaskMeta'
        }
    },
    title: 'ParseTaskInfo',
    required: [
        'status'
    ]
} as const;

export const ParseTaskMetaSchema = {
    type: 'object',
    properties: {
        fileName: {
            type: 'string'
        },
        textLength: {
            type: 'integer',
            format: 'int32'
        },
        llmStatus: {
            type: 'string'
        },
        llmError: {
            type: 'string'
        },
        strategy: {
            type: 'string'
        },
        startedAt: {
            type: 'string'
        },
        finishedAt: {
            type: 'string'
        },
        extractError: {
            type: 'string'
        }
    },
    title: 'ParseTaskMeta',
    required: [
        'fileName',
        'textLength',
        'llmStatus',
        'strategy'
    ]
} as const;

export const PostCompanyListReqSchema = {
    type: 'object',
    properties: {
        companyId: {
            type: 'string'
        },
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'PostCompanyListReq'
} as const;

export const PostCompanyListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/PostListData'
        }
    },
    title: 'PostCompanyListResp'
} as const;

export const PostCreateFromSnapshotRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'PostCreateFromSnapshotResp'
} as const;

export const PostCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'PostCreateResp'
} as const;

export const PostDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'PostDeleteResp'
} as const;

export const PostInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        resumeSnapshotId: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        companyId: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        feedback: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        }
    },
    title: 'PostInfo',
    required: [
        'id',
        'title',
        'companyTitle',
        'name',
        'resumeSnapshotId',
        'raw',
        'jobId',
        'companyId',
        'status',
        'feedback',
        'remark',
        'source',
        'userId',
        'createTime'
    ]
} as const;

export const PostListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/PostInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'PostListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const PostListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'PostListReq'
} as const;

export const PostListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/PostListData'
        }
    },
    title: 'PostListResp'
} as const;

export const PostStatusLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/StatusLogInfo'
            }
        }
    },
    title: 'PostStatusLogListResp'
} as const;

export const PostUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'PostUpdateResp'
} as const;

export const PostUserInterviewListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/InterviewWithJobInfo'
            }
        }
    },
    title: 'PostUserInterviewListResp'
} as const;

export const PostUserListReqSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        },
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'PostUserListReq',
    required: [
        'userId'
    ]
} as const;

export const PostUserListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserPostListData'
        }
    },
    title: 'PostUserListResp'
} as const;

export const PostUserOfferListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/OfferWithJobInfo'
            }
        }
    },
    title: 'PostUserOfferListResp'
} as const;

export const ResumeCompanyUploadRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/TaskIdData'
        }
    },
    title: 'ResumeCompanyUploadResp'
} as const;

export const ResumeCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'ResumeCreateResp'
} as const;

export const ResumeDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'ResumeDeleteResp'
} as const;

export const ResumeDetailReqSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        }
    },
    title: 'ResumeDetailReq',
    required: [
        'userId'
    ]
} as const;

export const ResumeDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeInfo'
        }
    },
    title: 'ResumeDetailResp'
} as const;

export const ResumeInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        cover: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        birthday: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        userId: {
            type: 'string'
        }
    },
    title: 'ResumeInfo',
    required: [
        'id',
        'cover',
        'name',
        'sex',
        'birthday',
        'raw',
        'education',
        'school',
        'email',
        'mobile',
        'summary',
        'skills',
        'experience',
        'projects',
        'eduDetail',
        'expectedSalary',
        'jobIntention',
        'source',
        'createTime',
        'userId'
    ]
} as const;

export const ResumeListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/ResumeInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'ResumeListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const ResumeListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'ResumeListReq'
} as const;

export const ResumeListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeListData'
        }
    },
    title: 'ResumeListResp'
} as const;

export const ResumeParseRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/TaskIdData'
        }
    },
    title: 'ResumeParseResp'
} as const;

export const ResumeParseResultRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ParseTaskInfo'
        }
    },
    title: 'ResumeParseResultResp'
} as const;

export const ResumeSnapshotDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'ResumeSnapshotDeleteResp'
} as const;

export const ResumeSnapshotDetailReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    title: 'ResumeSnapshotDetailReq',
    required: [
        'id'
    ]
} as const;

export const ResumeSnapshotDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeSnapshotInfo'
        }
    },
    title: 'ResumeSnapshotDetailResp'
} as const;

export const ResumeSnapshotInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        resumeId: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        birthday: {
            type: 'string'
        },
        cover: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        },
        tags: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        }
    },
    title: 'ResumeSnapshotInfo',
    required: [
        'id',
        'userId',
        'resumeId',
        'name',
        'sex',
        'birthday',
        'cover',
        'email',
        'mobile',
        'education',
        'school',
        'skills',
        'experience',
        'projects',
        'summary',
        'eduDetail',
        'expectedSalary',
        'jobIntention',
        'raw',
        'rating',
        'tags',
        'remark',
        'source',
        'createTime'
    ]
} as const;

export const ResumeSnapshotListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/ResumeSnapshotInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'ResumeSnapshotListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const ResumeSnapshotListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'ResumeSnapshotListReq'
} as const;

export const ResumeSnapshotListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/ResumeSnapshotListData'
        }
    },
    title: 'ResumeSnapshotListResp'
} as const;

export const ResumeSnapshotStatusLogListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/definitions/StatusLogInfo'
            }
        }
    },
    title: 'ResumeSnapshotStatusLogListResp'
} as const;

export const ResumeSnapshotUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'ResumeSnapshotUpdateResp'
} as const;

export const ResumeUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'ResumeUpdateResp'
} as const;

export const StatusLogInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        targetType: {
            type: 'string'
        },
        targetId: {
            type: 'string'
        },
        fromStatus: {
            type: 'string'
        },
        toStatus: {
            type: 'string'
        },
        feedback: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        operatorId: {
            type: 'string'
        },
        operatorName: {
            type: 'string'
        },
        createTime: {
            type: 'integer'
        }
    },
    title: 'StatusLogInfo',
    required: [
        'id',
        'targetType',
        'targetId',
        'fromStatus',
        'toStatus',
        'feedback',
        'remark',
        'operatorId',
        'operatorName',
        'createTime'
    ]
} as const;

export const StatusLogListReqSchema = {
    type: 'object',
    properties: {
        targetType: {
            type: 'string'
        },
        targetId: {
            type: 'string'
        }
    },
    title: 'StatusLogListReq',
    required: [
        'targetType',
        'targetId'
    ]
} as const;

export const TalentPoolAddReqSchema = {
    type: 'object',
    properties: {
        resumeSnapshotId: {
            type: 'string'
        },
        tags: {
            type: 'string'
        },
        remark: {
            type: 'string'
        }
    },
    title: 'TalentPoolAddReq',
    required: [
        'resumeSnapshotId'
    ]
} as const;

export const TalentPoolAddRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'TalentPoolAddResp'
} as const;

export const TalentPoolInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        resumeSnapshotId: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        },
        tags: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        }
    },
    title: 'TalentPoolInfo',
    required: [
        'id',
        'resumeSnapshotId',
        'name',
        'sex',
        'email',
        'mobile',
        'education',
        'school',
        'skills',
        'experience',
        'projects',
        'summary',
        'eduDetail',
        'expectedSalary',
        'jobIntention',
        'raw',
        'source',
        'rating',
        'tags',
        'remark',
        'createTime'
    ]
} as const;

export const TalentPoolListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/TalentPoolInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'TalentPoolListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const TalentPoolListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'TalentPoolListReq'
} as const;

export const TalentPoolListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/TalentPoolListData'
        }
    },
    title: 'TalentPoolListResp'
} as const;

export const TalentPoolRemoveReqSchema = {
    type: 'object',
    properties: {
        resumeSnapshotId: {
            type: 'string'
        }
    },
    title: 'TalentPoolRemoveReq',
    required: [
        'resumeSnapshotId'
    ]
} as const;

export const TalentPoolRemoveRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'TalentPoolRemoveResp'
} as const;

export const TalentPoolUpdateReqSchema = {
    type: 'object',
    properties: {
        resumeSnapshotId: {
            type: 'string'
        },
        tags: {
            type: 'string'
        },
        remark: {
            type: 'string'
        }
    },
    title: 'TalentPoolUpdateReq',
    required: [
        'resumeSnapshotId'
    ]
} as const;

export const TalentPoolUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'TalentPoolUpdateResp'
} as const;

export const TaskIdDataSchema = {
    type: 'object',
    properties: {
        taskId: {
            type: 'string'
        }
    },
    title: 'TaskIdData',
    required: [
        'taskId'
    ]
} as const;

export const UpdateCompanyReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        guimo: {
            type: 'string'
        },
        hangye: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        location: {
            type: 'string'
        }
    },
    title: 'UpdateCompanyReq',
    required: [
        'id'
    ]
} as const;

export const UpdateDepartmentReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        parentId: {
            type: 'string'
        }
    },
    title: 'UpdateDepartmentReq',
    required: [
        'id'
    ]
} as const;

export const UpdateInterviewReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        interviewerId: {
            type: 'string'
        },
        interviewerName: {
            type: 'string'
        },
        scheduledAt: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        result: {
            type: 'string'
        },
        score: {
            type: 'string'
        },
        evaluation: {
            type: 'string'
        }
    },
    title: 'UpdateInterviewReq',
    required: [
        'id'
    ]
} as const;

export const UpdateJobReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        jobCode: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        requirement: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        status: {
            type: 'integer'
        },
        location: {
            type: 'string'
        },
        address: {
            type: 'string'
        },
        minSalary: {
            type: 'integer'
        },
        maxSalary: {
            type: 'integer'
        },
        salaryUnit: {
            type: 'integer'
        },
        salaryShow: {
            type: 'string'
        },
        workExpe: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        recruitType: {
            type: 'string'
        },
        jobNature: {
            type: 'string'
        },
        departmentId: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        companyId: {
            type: 'string'
        }
    },
    title: 'UpdateJobReq',
    required: [
        'id'
    ]
} as const;

export const UpdateOfferReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        salary: {
            type: 'string'
        },
        level: {
            type: 'string'
        },
        joinDate: {
            type: 'string'
        },
        contractPeriod: {
            type: 'string'
        },
        probationPeriod: {
            type: 'string'
        },
        workLocation: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    },
    title: 'UpdateOfferReq',
    required: [
        'id'
    ]
} as const;

export const UpdatePostReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        resumeSnapshotId: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        companyId: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        feedback: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        source: {
            type: 'string'
        }
    },
    title: 'UpdatePostReq',
    required: [
        'id'
    ]
} as const;

export const UpdatePwdReqSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        },
        oldPassword: {
            type: 'string'
        },
        newPassword: {
            type: 'string'
        }
    },
    title: 'UpdatePwdReq',
    required: [
        'userId',
        'oldPassword',
        'newPassword'
    ]
} as const;

export const UpdateResumeReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        cover: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        birthday: {
            type: 'string'
        },
        raw: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        coverFile: {
            type: 'string'
        },
        rawFile: {
            type: 'string'
        }
    },
    title: 'UpdateResumeReq',
    required: [
        'id',
        'userId'
    ]
} as const;

export const UpdateResumeSnapshotReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sex: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        education: {
            type: 'string'
        },
        school: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        skills: {
            type: 'string'
        },
        experience: {
            type: 'string'
        },
        projects: {
            type: 'string'
        },
        eduDetail: {
            type: 'string'
        },
        expectedSalary: {
            type: 'string'
        },
        jobIntention: {
            type: 'string'
        },
        rating: {
            type: 'string'
        },
        tags: {
            type: 'string'
        },
        remark: {
            type: 'string'
        },
        source: {
            type: 'string'
        }
    },
    title: 'UpdateResumeSnapshotReq',
    required: [
        'id'
    ]
} as const;

export const UpdateUserInfoReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        nickname: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        pushEmail: {
            type: 'string'
        },
        pushSwitch: {
            type: 'string'
        }
    },
    title: 'UpdateUserInfoReq',
    required: [
        'id'
    ]
} as const;

export const UpdateUserReqSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        nickname: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        pushEmail: {
            type: 'string'
        },
        pushSwitch: {
            type: 'string'
        }
    },
    title: 'UpdateUserReq',
    required: [
        'id'
    ]
} as const;

export const UserCreateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'UserCreateResp'
} as const;

export const UserDeleteRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'UserDeleteResp'
} as const;

export const UserDetailReqSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        }
    },
    title: 'UserDetailReq',
    required: [
        'userId'
    ]
} as const;

export const UserDetailRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserInfo'
        }
    },
    title: 'UserDetailResp'
} as const;

export const UserInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        nickname: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        token: {
            type: 'string'
        },
        createTime: {
            type: 'string'
        },
        pushEmail: {
            type: 'string'
        },
        pushSwitch: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        }
    },
    title: 'UserInfo',
    required: [
        'id',
        'username',
        'password',
        'nickname',
        'mobile',
        'email',
        'role',
        'status',
        'token',
        'createTime',
        'pushEmail',
        'pushSwitch'
    ]
} as const;

export const UserInterviewListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'UserInterviewListReq'
} as const;

export const UserListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/UserInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'UserListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const UserListReqSchema = {
    type: 'object',
    properties: {
        keyword: {
            type: 'string'
        },
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'UserListReq'
} as const;

export const UserListRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserListData'
        }
    },
    title: 'UserListResp'
} as const;

export const UserLoginReqSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    title: 'UserLoginReq',
    required: [
        'username',
        'password'
    ]
} as const;

export const UserLoginRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserInfo'
        }
    },
    title: 'UserLoginResp'
} as const;

export const UserLoginResp2Schema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        },
        data: {
            $ref: '#/definitions/UserInfo'
        }
    },
    title: 'UserLoginResp2'
} as const;

export const UserOfferListReqSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'integer',
            default: '1'
        },
        pageSize: {
            type: 'integer',
            default: '10'
        }
    },
    title: 'UserOfferListReq'
} as const;

export const UserPostItemInfoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        jobId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        feedback: {
            type: 'string'
        },
        source: {
            type: 'string'
        },
        companyTitle: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        categoryTitle: {
            type: 'string'
        },
        departmentTitle: {
            type: 'string'
        }
    },
    title: 'UserPostItemInfo',
    required: [
        'id',
        'jobId',
        'title',
        'status',
        'feedback',
        'source',
        'companyTitle',
        'location',
        'categoryTitle',
        'departmentTitle'
    ]
} as const;

export const UserPostListDataSchema = {
    type: 'object',
    properties: {
        list: {
            type: 'array',
            items: {
                $ref: '#/definitions/UserPostItemInfo'
            }
        },
        total: {
            type: 'integer'
        },
        page: {
            type: 'integer'
        },
        pageSize: {
            type: 'integer'
        }
    },
    title: 'UserPostListData',
    required: [
        'list',
        'total',
        'page',
        'pageSize'
    ]
} as const;

export const UserRegisterReqSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        rePassword: {
            type: 'string'
        },
        nickname: {
            type: 'string'
        },
        mobile: {
            type: 'string'
        },
        email: {
            type: 'string'
        }
    },
    title: 'UserRegisterReq',
    required: [
        'username',
        'password',
        'rePassword'
    ]
} as const;

export const UserRegisterRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'UserRegisterResp'
} as const;

export const UserUpdatePwdRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'UserUpdatePwdResp'
} as const;

export const UserUpdateRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'UserUpdateResp'
} as const;

export const UserUpdateUserInfoRespSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer'
        },
        msg: {
            type: 'string'
        },
        trace: {
            type: 'string'
        },
        timestamp: {
            type: 'integer'
        }
    },
    title: 'UserUpdateUserInfoResp'
} as const;
