// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `https://${string}` | (string & {});
};

export type CompanyCompanyCreateData = {
    body: {
        description?: string;
        guimo?: string;
        hangye?: string;
        location?: string;
        title: string;
    };
    path?: never;
    query?: never;
    url: '/api/company/create';
};

export type CompanyCompanyCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type CompanyCompanyCreateResponse = CompanyCompanyCreateResponses[keyof CompanyCompanyCreateResponses];

export type CompanyCompanyDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/company/delete';
};

export type CompanyCompanyDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type CompanyCompanyDeleteResponse = CompanyCompanyDeleteResponses[keyof CompanyCompanyDeleteResponses];

export type CompanyCompanyListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/company/list';
};

export type CompanyCompanyListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                description: string;
                guimo: string;
                hangye: string;
                id: string;
                location: string;
                title: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type CompanyCompanyListResponse = CompanyCompanyListResponses[keyof CompanyCompanyListResponses];

export type CompanyCompanyUpdateData = {
    body: {
        description?: string;
        guimo?: string;
        hangye?: string;
        id: string;
        location?: string;
        title?: string;
    };
    path?: never;
    query?: never;
    url: '/api/company/update';
};

export type CompanyCompanyUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type CompanyCompanyUpdateResponse = CompanyCompanyUpdateResponses[keyof CompanyCompanyUpdateResponses];

export type DepartmentDepartmentCreateData = {
    body: {
        description?: string;
        parentId?: string;
        title: string;
    };
    path?: never;
    query?: never;
    url: '/api/department/create';
};

export type DepartmentDepartmentCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type DepartmentDepartmentCreateResponse = DepartmentDepartmentCreateResponses[keyof DepartmentDepartmentCreateResponses];

export type DepartmentDepartmentDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/department/delete';
};

export type DepartmentDepartmentDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type DepartmentDepartmentDeleteResponse = DepartmentDepartmentDeleteResponses[keyof DepartmentDepartmentDeleteResponses];

export type DepartmentDepartmentListData = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/department/list';
};

export type DepartmentDepartmentListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                createTime: string;
                description: string;
                id: string;
                parentId: string;
                title: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type DepartmentDepartmentListResponse = DepartmentDepartmentListResponses[keyof DepartmentDepartmentListResponses];

export type DepartmentDepartmentUpdateData = {
    body: {
        description?: string;
        id: string;
        parentId?: string;
        title?: string;
    };
    path?: never;
    query?: never;
    url: '/api/department/update';
};

export type DepartmentDepartmentUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type DepartmentDepartmentUpdateResponse = DepartmentDepartmentUpdateResponses[keyof DepartmentDepartmentUpdateResponses];

export type InterviewInterviewCreateData = {
    body: {
        evaluation?: string;
        interviewerId?: string;
        interviewerName?: string;
        location?: string;
        postId: string;
        result?: string;
        round: string;
        scheduledAt?: string;
        score?: string;
        type?: string;
    };
    path?: never;
    query?: never;
    url: '/api/interview/create';
};

export type InterviewInterviewCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type InterviewInterviewCreateResponse = InterviewInterviewCreateResponses[keyof InterviewInterviewCreateResponses];

export type InterviewInterviewListData = {
    body?: never;
    path?: never;
    query: {
        postId: string;
    };
    url: '/api/interview/list';
};

export type InterviewInterviewListResponses = {
    200: {
        code?: number;
        data?: Array<{
            createTime: string;
            evaluation: string;
            id: string;
            interviewerId: string;
            interviewerName: string;
            location: string;
            postId: string;
            result: string;
            round: string;
            scheduledAt: string;
            score: string;
            type: string;
        }>;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type InterviewInterviewListResponse = InterviewInterviewListResponses[keyof InterviewInterviewListResponses];

export type InterviewInterviewUpdateData = {
    body: {
        evaluation?: string;
        id: string;
        interviewerId?: string;
        interviewerName?: string;
        location?: string;
        result?: string;
        scheduledAt?: string;
        score?: string;
        type?: string;
    };
    path?: never;
    query?: never;
    url: '/api/interview/update';
};

export type InterviewInterviewUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type InterviewInterviewUpdateResponse = InterviewInterviewUpdateResponses[keyof InterviewInterviewUpdateResponses];

export type JobJobCategoryListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/job/categoryList';
};

export type JobJobCategoryListResponses = {
    200: {
        code?: number;
        data?: {
            categories: Array<string>;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type JobJobCategoryListResponse = JobJobCategoryListResponses[keyof JobJobCategoryListResponses];

export type JobJobCreateData = {
    body: {
        address?: string;
        category?: string;
        companyId?: string;
        departmentId?: string;
        description?: string;
        education?: string;
        jobCode?: string;
        jobNature?: string;
        location?: string;
        maxSalary?: number;
        minSalary?: number;
        recruitType?: string;
        requirement?: string;
        salaryShow?: string;
        salaryUnit?: number;
        status?: number;
        title: string;
        userId?: string;
        workExpe?: string;
    };
    path?: never;
    query?: never;
    url: '/api/job/create';
};

export type JobJobCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type JobJobCreateResponse = JobJobCreateResponses[keyof JobJobCreateResponses];

export type JobJobDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/job/delete';
};

export type JobJobDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type JobJobDeleteResponse = JobJobDeleteResponses[keyof JobJobDeleteResponses];

export type JobJobDetailData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/api/job/detail';
};

export type JobJobDetailResponses = {
    200: {
        code?: number;
        data?: {
            address: string;
            category: string;
            companyId: string;
            companyTitle: string;
            createTime: string;
            departmentId: string;
            departmentTitle: string;
            description: string;
            education: string;
            id: string;
            jobCode: string;
            jobNature: string;
            location: string;
            maxSalary: number;
            minSalary: number;
            pv: number;
            recruitType: string;
            requirement: string;
            salaryShow: string;
            salaryUnit: number;
            status: number;
            title: string;
            updateTime: string;
            workExpe: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type JobJobDetailResponse = JobJobDetailResponses[keyof JobJobDetailResponses];

export type JobJobListData = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        sort?: string;
        category?: string;
        recruitType?: string;
        jobNature?: string;
        salaryMin?: number;
        salaryMax?: number;
        page?: number;
        pageSize?: number;
    };
    url: '/api/job/list';
};

export type JobJobListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                address: string;
                category: string;
                companyId: string;
                companyTitle: string;
                createTime: string;
                departmentId: string;
                departmentTitle: string;
                description: string;
                education: string;
                id: string;
                jobCode: string;
                jobNature: string;
                location: string;
                maxSalary: number;
                minSalary: number;
                pv: number;
                recruitType: string;
                requirement: string;
                salaryShow: string;
                salaryUnit: number;
                status: number;
                title: string;
                updateTime: string;
                workExpe: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type JobJobListResponse = JobJobListResponses[keyof JobJobListResponses];

export type JobJobUserListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        keyword?: string;
    };
    url: '/api/job/listUserJobApi';
};

export type JobJobUserListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                address: string;
                category: string;
                companyId: string;
                companyTitle: string;
                createTime: string;
                departmentId: string;
                departmentTitle: string;
                description: string;
                education: string;
                id: string;
                jobCode: string;
                jobNature: string;
                location: string;
                maxSalary: number;
                minSalary: number;
                pv: number;
                recruitType: string;
                requirement: string;
                salaryShow: string;
                salaryUnit: number;
                status: number;
                title: string;
                updateTime: string;
                workExpe: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type JobJobUserListResponse = JobJobUserListResponses[keyof JobJobUserListResponses];

export type JobJobUpdateData = {
    body: {
        address?: string;
        category?: string;
        companyId?: string;
        departmentId?: string;
        description?: string;
        education?: string;
        id: string;
        jobCode?: string;
        jobNature?: string;
        location?: string;
        maxSalary?: number;
        minSalary?: number;
        recruitType?: string;
        requirement?: string;
        salaryShow?: string;
        salaryUnit?: number;
        status?: number;
        title?: string;
        userId?: string;
        workExpe?: string;
    };
    path?: never;
    query?: never;
    url: '/api/job/update';
};

export type JobJobUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type JobJobUpdateResponse = JobJobUpdateResponses[keyof JobJobUpdateResponses];

export type OfferOfferCreateData = {
    body: {
        contractPeriod?: string;
        joinDate?: string;
        level?: string;
        postId: string;
        probationPeriod?: string;
        salary?: string;
        workLocation?: string;
    };
    path?: never;
    query?: never;
    url: '/api/offer/create';
};

export type OfferOfferCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type OfferOfferCreateResponse = OfferOfferCreateResponses[keyof OfferOfferCreateResponses];

export type OfferOfferDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/offer/delete';
};

export type OfferOfferDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type OfferOfferDeleteResponse = OfferOfferDeleteResponses[keyof OfferOfferDeleteResponses];

export type OfferOfferDetailData = {
    body?: never;
    path?: never;
    query: {
        postId: string;
    };
    url: '/api/offer/detail';
};

export type OfferOfferDetailResponses = {
    200: {
        code?: number;
        data?: {
            contractPeriod: string;
            createTime: string;
            id: string;
            joinDate: string;
            level: string;
            postId: string;
            probationPeriod: string;
            salary: string;
            status: string;
            workLocation: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type OfferOfferDetailResponse = OfferOfferDetailResponses[keyof OfferOfferDetailResponses];

export type OfferOfferListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/offer/list';
};

export type OfferOfferListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                contractPeriod: string;
                createTime: string;
                id: string;
                joinDate: string;
                level: string;
                postId: string;
                probationPeriod: string;
                salary: string;
                status: string;
                workLocation: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type OfferOfferListResponse = OfferOfferListResponses[keyof OfferOfferListResponses];

export type OfferOfferUpdateData = {
    body: {
        contractPeriod?: string;
        id: string;
        joinDate?: string;
        level?: string;
        probationPeriod?: string;
        salary?: string;
        status?: string;
        workLocation?: string;
    };
    path?: never;
    query?: never;
    url: '/api/offer/update';
};

export type OfferOfferUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type OfferOfferUpdateResponse = OfferOfferUpdateResponses[keyof OfferOfferUpdateResponses];

export type OplogOpLogListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/opLog/list';
};

export type OplogOpLogListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                accessTime: string;
                bizCode: number;
                bizMsg: string;
                id: string;
                reContent: string;
                reIp: string;
                reMethod: string;
                reTime: string;
                reUa: string;
                reUrl: string;
                requestId: string;
                success: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type OplogOpLogListResponse = OplogOpLogListResponses[keyof OplogOpLogListResponses];

export type OplogLoginLogListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/opLog/loginLogList';
};

export type OplogLoginLogListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                accessTime: string;
                bizCode: number;
                bizMsg: string;
                id: string;
                reContent: string;
                reIp: string;
                reMethod: string;
                reTime: string;
                reUa: string;
                reUrl: string;
                requestId: string;
                success: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type OplogLoginLogListResponse = OplogLoginLogListResponses[keyof OplogLoginLogListResponses];

export type PostPostCreateData = {
    body: {
        companyId?: string;
        jobId?: string;
        resumeId?: string;
        source?: string;
        userId: string;
    };
    path?: never;
    query?: never;
    url: '/api/post/create';
};

export type PostPostCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostCreateResponse = PostPostCreateResponses[keyof PostPostCreateResponses];

export type PostPostCreateFromSnapshotData = {
    body: {
        jobId: string;
        resumeSnapshotId: string;
    };
    path?: never;
    query?: never;
    url: '/api/post/createFromSnapshot';
};

export type PostPostCreateFromSnapshotResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostCreateFromSnapshotResponse = PostPostCreateFromSnapshotResponses[keyof PostPostCreateFromSnapshotResponses];

export type PostPostDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/post/delete';
};

export type PostPostDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostDeleteResponse = PostPostDeleteResponses[keyof PostPostDeleteResponses];

export type PostPostListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/list';
};

export type PostPostListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                companyId: string;
                companyTitle: string;
                createTime: string;
                feedback: string;
                id: string;
                jobId: string;
                name: string;
                raw: string;
                remark: string;
                resumeSnapshotId: string;
                source: string;
                status: string;
                title: string;
                userId: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostListResponse = PostPostListResponses[keyof PostPostListResponses];

export type PostPostCompanyListData = {
    body?: never;
    path?: never;
    query: {
        companyId: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/listCompanyPostApi';
};

export type PostPostCompanyListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                companyId: string;
                companyTitle: string;
                createTime: string;
                feedback: string;
                id: string;
                jobId: string;
                name: string;
                raw: string;
                remark: string;
                resumeSnapshotId: string;
                source: string;
                status: string;
                title: string;
                userId: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostCompanyListResponse = PostPostCompanyListResponses[keyof PostPostCompanyListResponses];

export type PostPostUserListData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/listUserPostApi';
};

export type PostPostUserListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                categoryTitle: string;
                companyTitle: string;
                departmentTitle: string;
                feedback: string;
                id: string;
                jobId: string;
                location: string;
                source: string;
                status: string;
                title: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostUserListResponse = PostPostUserListResponses[keyof PostPostUserListResponses];

export type PostPostStatusLogListData = {
    body?: never;
    path?: never;
    query: {
        targetType: string;
        targetId: string;
    };
    url: '/api/post/statusLogList';
};

export type PostPostStatusLogListResponses = {
    200: {
        code?: number;
        data?: Array<{
            createTime: number;
            feedback: string;
            fromStatus: string;
            id: string;
            operatorId: string;
            operatorName: string;
            remark: string;
            targetId: string;
            targetType: string;
            toStatus: string;
        }>;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostStatusLogListResponse = PostPostStatusLogListResponses[keyof PostPostStatusLogListResponses];

export type PostPostUpdateData = {
    body: {
        companyId?: string;
        feedback?: string;
        id: string;
        jobId?: string;
        remark?: string;
        resumeSnapshotId?: string;
        source?: string;
        status?: string;
    };
    path?: never;
    query?: never;
    url: '/api/post/update';
};

export type PostPostUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostUpdateResponse = PostPostUpdateResponses[keyof PostPostUpdateResponses];

export type PostPostUserInterviewListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/userInterviewList';
};

export type PostPostUserInterviewListResponses = {
    200: {
        code?: number;
        data?: Array<{
            categoryTitle: string;
            companyTitle: string;
            createTime: string;
            departmentTitle: string;
            evaluation: string;
            id: string;
            interviewerId: string;
            interviewerName: string;
            jobId: string;
            jobLocation: string;
            jobTitle: string;
            location: string;
            postId: string;
            postStatus: string;
            result: string;
            round: string;
            scheduledAt: string;
            score: string;
            type: string;
        }>;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostUserInterviewListResponse = PostPostUserInterviewListResponses[keyof PostPostUserInterviewListResponses];

export type PostPostUserOfferListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/userOfferList';
};

export type PostPostUserOfferListResponses = {
    200: {
        code?: number;
        data?: Array<{
            categoryTitle: string;
            companyTitle: string;
            contractPeriod: string;
            createTime: string;
            departmentTitle: string;
            id: string;
            jobId: string;
            jobLocation: string;
            jobTitle: string;
            joinDate: string;
            level: string;
            postId: string;
            postStatus: string;
            probationPeriod: string;
            salary: string;
            status: string;
            workLocation: string;
        }>;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type PostPostUserOfferListResponse = PostPostUserOfferListResponses[keyof PostPostUserOfferListResponses];

export type ResumeResumeCompanyUploadData = {
    body?: {
        rawFile?: string;
        source?: string;
        addToTalentPool?: string;
    };
    path?: never;
    query?: never;
    url: '/api/resume/companyUpload';
};

export type ResumeResumeCompanyUploadResponses = {
    200: {
        code?: number;
        data?: {
            taskId: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeCompanyUploadResponse = ResumeResumeCompanyUploadResponses[keyof ResumeResumeCompanyUploadResponses];

export type ResumeResumeCreateData = {
    body: {
        name: string;
        sex?: string;
        birthday?: string;
        raw?: string;
        education?: string;
        school?: string;
        email?: string;
        mobile?: string;
        userId: string;
        summary?: string;
        skills?: string;
        experience?: string;
        projects?: string;
        eduDetail?: string;
        expectedSalary?: string;
        jobIntention?: string;
        source?: string;
        coverFile?: string;
        rawFile?: string;
    };
    path?: never;
    query?: never;
    url: '/api/resume/create';
};

export type ResumeResumeCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeCreateResponse = ResumeResumeCreateResponses[keyof ResumeResumeCreateResponses];

export type ResumeResumeDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/resume/delete';
};

export type ResumeResumeDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeDeleteResponse = ResumeResumeDeleteResponses[keyof ResumeResumeDeleteResponses];

export type ResumeResumeDetailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
    };
    url: '/api/resume/detail';
};

export type ResumeResumeDetailResponses = {
    200: {
        code?: number;
        data?: {
            birthday: string;
            cover: string;
            createTime: string;
            eduDetail: string;
            education: string;
            email: string;
            expectedSalary: string;
            experience: string;
            id: string;
            jobIntention: string;
            mobile: string;
            name: string;
            projects: string;
            raw: string;
            school: string;
            sex: string;
            skills: string;
            source: string;
            summary: string;
            userId: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeDetailResponse = ResumeResumeDetailResponses[keyof ResumeResumeDetailResponses];

export type ResumeResumeListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/resume/list';
};

export type ResumeResumeListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                birthday: string;
                cover: string;
                createTime: string;
                eduDetail: string;
                education: string;
                email: string;
                expectedSalary: string;
                experience: string;
                id: string;
                jobIntention: string;
                mobile: string;
                name: string;
                projects: string;
                raw: string;
                school: string;
                sex: string;
                skills: string;
                source: string;
                summary: string;
                userId: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeListResponse = ResumeResumeListResponses[keyof ResumeResumeListResponses];

export type ResumeResumeParseData = {
    body?: {
        rawFile?: string;
    };
    path?: never;
    query?: never;
    url: '/api/resume/parse';
};

export type ResumeResumeParseResponses = {
    200: {
        code?: number;
        data?: {
            taskId: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeParseResponse = ResumeResumeParseResponses[keyof ResumeResumeParseResponses];

export type ResumeResumeParseResultData = {
    body?: never;
    path?: never;
    query: {
        taskId: string;
    };
    url: '/api/resume/parseResult';
};

export type ResumeResumeParseResultResponses = {
    200: {
        code?: number;
        data?: {
            meta: {
                extractError: string;
                fileName: string;
                finishedAt: string;
                llmError: string;
                llmStatus: string;
                startedAt: string;
                strategy: string;
                textLength: number;
            };
            msg: string;
            result: unknown;
            status: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeParseResultResponse = ResumeResumeParseResultResponses[keyof ResumeResumeParseResultResponses];

export type ResumeResumeUpdateData = {
    body: {
        id: string;
        cover?: string;
        name?: string;
        sex?: string;
        birthday?: string;
        raw?: string;
        education?: string;
        school?: string;
        email?: string;
        mobile?: string;
        userId: string;
        summary?: string;
        skills?: string;
        experience?: string;
        projects?: string;
        eduDetail?: string;
        expectedSalary?: string;
        jobIntention?: string;
        source?: string;
        coverFile?: string;
        rawFile?: string;
    };
    path?: never;
    query?: never;
    url: '/api/resume/update';
};

export type ResumeResumeUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumeResumeUpdateResponse = ResumeResumeUpdateResponses[keyof ResumeResumeUpdateResponses];

export type ResumesnapshotResumeSnapshotDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/resumeSnapshot/delete';
};

export type ResumesnapshotResumeSnapshotDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumesnapshotResumeSnapshotDeleteResponse = ResumesnapshotResumeSnapshotDeleteResponses[keyof ResumesnapshotResumeSnapshotDeleteResponses];

export type ResumesnapshotResumeSnapshotDetailData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/api/resumeSnapshot/detail';
};

export type ResumesnapshotResumeSnapshotDetailResponses = {
    200: {
        code?: number;
        data?: {
            birthday: string;
            cover: string;
            createTime: string;
            eduDetail: string;
            education: string;
            email: string;
            expectedSalary: string;
            experience: string;
            id: string;
            jobIntention: string;
            mobile: string;
            name: string;
            projects: string;
            rating: number;
            raw: string;
            remark: string;
            resumeId: string;
            school: string;
            sex: string;
            skills: string;
            source: string;
            summary: string;
            tags: string;
            userId: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumesnapshotResumeSnapshotDetailResponse = ResumesnapshotResumeSnapshotDetailResponses[keyof ResumesnapshotResumeSnapshotDetailResponses];

export type ResumesnapshotResumeSnapshotListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/resumeSnapshot/list';
};

export type ResumesnapshotResumeSnapshotListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                birthday: string;
                cover: string;
                createTime: string;
                eduDetail: string;
                education: string;
                email: string;
                expectedSalary: string;
                experience: string;
                id: string;
                jobIntention: string;
                mobile: string;
                name: string;
                projects: string;
                rating: number;
                raw: string;
                remark: string;
                resumeId: string;
                school: string;
                sex: string;
                skills: string;
                source: string;
                summary: string;
                tags: string;
                userId: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumesnapshotResumeSnapshotListResponse = ResumesnapshotResumeSnapshotListResponses[keyof ResumesnapshotResumeSnapshotListResponses];

export type ResumesnapshotResumeSnapshotStatusLogListData = {
    body?: never;
    path?: never;
    query: {
        targetType: string;
        targetId: string;
    };
    url: '/api/resumeSnapshot/statusLogList';
};

export type ResumesnapshotResumeSnapshotStatusLogListResponses = {
    200: {
        code?: number;
        data?: Array<{
            createTime: number;
            feedback: string;
            fromStatus: string;
            id: string;
            operatorId: string;
            operatorName: string;
            remark: string;
            targetId: string;
            targetType: string;
            toStatus: string;
        }>;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumesnapshotResumeSnapshotStatusLogListResponse = ResumesnapshotResumeSnapshotStatusLogListResponses[keyof ResumesnapshotResumeSnapshotStatusLogListResponses];

export type ResumesnapshotResumeSnapshotUpdateData = {
    body: {
        eduDetail?: string;
        education?: string;
        email?: string;
        expectedSalary?: string;
        experience?: string;
        id: string;
        jobIntention?: string;
        mobile?: string;
        name?: string;
        projects?: string;
        rating?: string;
        remark?: string;
        school?: string;
        sex?: string;
        skills?: string;
        source?: string;
        summary?: string;
        tags?: string;
    };
    path?: never;
    query?: never;
    url: '/api/resumeSnapshot/update';
};

export type ResumesnapshotResumeSnapshotUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type ResumesnapshotResumeSnapshotUpdateResponse = ResumesnapshotResumeSnapshotUpdateResponses[keyof ResumesnapshotResumeSnapshotUpdateResponses];

export type TalentpoolTalentPoolAddData = {
    body: {
        remark?: string;
        resumeSnapshotId: string;
        tags?: string;
    };
    path?: never;
    query?: never;
    url: '/api/talentPool/add';
};

export type TalentpoolTalentPoolAddResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type TalentpoolTalentPoolAddResponse = TalentpoolTalentPoolAddResponses[keyof TalentpoolTalentPoolAddResponses];

export type TalentpoolTalentPoolListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/talentPool/list';
};

export type TalentpoolTalentPoolListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                createTime: string;
                education: string;
                email: string;
                id: string;
                mobile: string;
                name: string;
                rating: number;
                remark: string;
                resumeSnapshotId: string;
                tags: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type TalentpoolTalentPoolListResponse = TalentpoolTalentPoolListResponses[keyof TalentpoolTalentPoolListResponses];

export type TalentpoolTalentPoolRemoveData = {
    body: {
        resumeSnapshotId: string;
    };
    path?: never;
    query?: never;
    url: '/api/talentPool/remove';
};

export type TalentpoolTalentPoolRemoveResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type TalentpoolTalentPoolRemoveResponse = TalentpoolTalentPoolRemoveResponses[keyof TalentpoolTalentPoolRemoveResponses];

export type TalentpoolTalentPoolUpdateData = {
    body: {
        remark?: string;
        resumeSnapshotId: string;
        tags?: string;
    };
    path?: never;
    query?: never;
    url: '/api/talentPool/update';
};

export type TalentpoolTalentPoolUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type TalentpoolTalentPoolUpdateResponse = TalentpoolTalentPoolUpdateResponses[keyof TalentpoolTalentPoolUpdateResponses];

export type UserUserCreateData = {
    body: {
        email?: string;
        mobile?: string;
        nickname?: string;
        password: string;
        role?: string;
        status?: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/create';
};

export type UserUserCreateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserCreateResponse = UserUserCreateResponses[keyof UserUserCreateResponses];

export type UserUserDeleteData = {
    body: {
        ids: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/delete';
};

export type UserUserDeleteResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserDeleteResponse = UserUserDeleteResponses[keyof UserUserDeleteResponses];

export type UserUserDetailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
    };
    url: '/api/user/detail';
};

export type UserUserDetailResponses = {
    200: {
        code?: number;
        data?: {
            avatar: string;
            createTime: string;
            email: string;
            id: string;
            mobile: string;
            nickname: string;
            password: string;
            pushEmail: string;
            pushSwitch: string;
            role: string;
            status: string;
            token: string;
            username: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserDetailResponse = UserUserDetailResponses[keyof UserUserDetailResponses];

export type UserUserListData = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/user/list';
};

export type UserUserListResponses = {
    200: {
        code?: number;
        data?: {
            list: Array<{
                avatar: string;
                createTime: string;
                email: string;
                id: string;
                mobile: string;
                nickname: string;
                password: string;
                pushEmail: string;
                pushSwitch: string;
                role: string;
                status: string;
                token: string;
                username: string;
            }>;
            page: number;
            pageSize: number;
            total: number;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserListResponse = UserUserListResponses[keyof UserUserListResponses];

export type UserUserLoginData = {
    body: {
        password: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/login';
};

export type UserUserLoginResponses = {
    200: {
        code?: number;
        data?: {
            avatar: string;
            createTime: string;
            email: string;
            id: string;
            mobile: string;
            nickname: string;
            password: string;
            pushEmail: string;
            pushSwitch: string;
            role: string;
            status: string;
            token: string;
            username: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserLoginResponse = UserUserLoginResponses[keyof UserUserLoginResponses];

export type UserUserUpdateData = {
    body: {
        email?: string;
        id: string;
        mobile?: string;
        nickname?: string;
        password?: string;
        pushEmail?: string;
        pushSwitch?: string;
        role?: string;
        status?: string;
        username?: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/update';
};

export type UserUserUpdateResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserUpdateResponse = UserUserUpdateResponses[keyof UserUserUpdateResponses];

export type UserUserUpdatePwdData = {
    body: {
        newPassword: string;
        oldPassword: string;
        userId: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/updatePwd';
};

export type UserUserUpdatePwdResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserUpdatePwdResponse = UserUserUpdatePwdResponses[keyof UserUserUpdatePwdResponses];

export type UserUserUpdateUserInfoData = {
    body: {
        email?: string;
        id: string;
        mobile?: string;
        nickname?: string;
        pushEmail?: string;
        pushSwitch?: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/updateUserInfo';
};

export type UserUserUpdateUserInfoResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserUpdateUserInfoResponse = UserUserUpdateUserInfoResponses[keyof UserUserUpdateUserInfoResponses];

export type UserUserUserLoginData = {
    body: {
        password: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/userLogin';
};

export type UserUserUserLoginResponses = {
    200: {
        code?: number;
        data?: {
            avatar: string;
            createTime: string;
            email: string;
            id: string;
            mobile: string;
            nickname: string;
            password: string;
            pushEmail: string;
            pushSwitch: string;
            role: string;
            status: string;
            token: string;
            username: string;
        };
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserUserLoginResponse = UserUserUserLoginResponses[keyof UserUserUserLoginResponses];

export type UserUserRegisterData = {
    body: {
        email?: string;
        mobile?: string;
        nickname?: string;
        password: string;
        rePassword: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/api/user/userRegister';
};

export type UserUserRegisterResponses = {
    200: {
        code?: number;
        msg?: string;
        timestamp?: number;
        trace?: string;
    };
};

export type UserUserRegisterResponse = UserUserRegisterResponses[keyof UserUserRegisterResponses];
