// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:9100/' | 'https://127.0.0.1:9100/' | (string & {});
};

/**
 * BaseResp
 */
export type BaseResp = {
    code: number;
    msg: string;
    trace?: string;
    timestamp: number;
};

/**
 * CategoryListData
 */
export type CategoryListData = {
    categories: Array<string>;
};

/**
 * CompanyCreateResp
 */
export type CompanyCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * CompanyDeleteResp
 */
export type CompanyDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * CompanyInfo
 */
export type CompanyInfo = {
    id: string;
    title: string;
    guimo: string;
    hangye: string;
    description: string;
    location: string;
};

/**
 * CompanyListData
 */
export type CompanyListData = {
    list: Array<CompanyInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * CompanyListReq
 */
export type CompanyListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * CompanyListResp
 */
export type CompanyListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: CompanyListData;
};

/**
 * CompanyUpdateResp
 */
export type CompanyUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * CompanyUploadResumeReq
 */
export type CompanyUploadResumeReq = {
    rawFile?: string;
    source?: string;
    addToTalentPool?: string;
};

/**
 * CreateCompanyReq
 */
export type CreateCompanyReq = {
    title: string;
    guimo?: string;
    hangye?: string;
    description?: string;
    location?: string;
};

/**
 * CreateDepartmentReq
 */
export type CreateDepartmentReq = {
    title: string;
    description?: string;
    parentId?: string;
};

/**
 * CreateInterviewReq
 */
export type CreateInterviewReq = {
    postId: string;
    round: string;
    interviewerId?: string;
    interviewerName?: string;
    scheduledAt?: string;
    location?: string;
    type?: string;
    result?: string;
    score?: string;
    evaluation?: string;
};

/**
 * CreateJobReq
 */
export type CreateJobReq = {
    title: string;
    jobCode?: string;
    description?: string;
    requirement?: string;
    education?: string;
    status?: number;
    location?: string;
    address?: string;
    minSalary?: number;
    maxSalary?: number;
    salaryUnit?: number;
    salaryShow?: string;
    workExpe?: string;
    category?: string;
    recruitType?: string;
    jobNature?: string;
    departmentId?: string;
    userId?: string;
    companyId?: string;
};

/**
 * CreateOfferReq
 */
export type CreateOfferReq = {
    postId: string;
    salary?: string;
    level?: string;
    joinDate?: string;
    contractPeriod?: string;
    probationPeriod?: string;
    workLocation?: string;
};

/**
 * CreatePostFromSnapshotReq
 */
export type CreatePostFromSnapshotReq = {
    resumeSnapshotId: string;
    jobId: string;
};

/**
 * CreatePostReq
 */
export type CreatePostReq = {
    resumeId?: string;
    userId: string;
    jobId?: string;
    companyId?: string;
    source?: string;
};

/**
 * CreateResumeReq
 */
export type CreateResumeReq = {
    name: string;
    sex?: string;
    birthday?: string;
    raw?: string;
    education?: string;
    school?: string;
    email?: string;
    mobile?: string;
    userId: string;
    summary?: string;
    skills?: string;
    experience?: string;
    projects?: string;
    eduDetail?: string;
    expectedSalary?: string;
    jobIntention?: string;
    source?: string;
    coverFile?: string;
    rawFile?: string;
};

/**
 * CreateUserReq
 */
export type CreateUserReq = {
    username: string;
    password: string;
    nickname?: string;
    mobile?: string;
    email?: string;
    role?: string;
    status?: string;
};

/**
 * DeleteReq
 */
export type DeleteReq = {
    ids: string;
};

/**
 * DepartmentCreateResp
 */
export type DepartmentCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * DepartmentDeleteResp
 */
export type DepartmentDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * DepartmentInfo
 */
export type DepartmentInfo = {
    id: string;
    title: string;
    description: string;
    parentId: string;
    createTime: string;
};

/**
 * DepartmentListData
 */
export type DepartmentListData = {
    list: Array<DepartmentInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * DepartmentListReq
 */
export type DepartmentListReq = {
    keyword?: string;
    page?: number;
    pageSize?: number;
};

/**
 * DepartmentListResp
 */
export type DepartmentListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: DepartmentListData;
};

/**
 * DepartmentUpdateResp
 */
export type DepartmentUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * InterviewCreateResp
 */
export type InterviewCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * InterviewInfo
 */
export type InterviewInfo = {
    id: string;
    postId: string;
    round: string;
    interviewerId: string;
    interviewerName: string;
    scheduledAt: string;
    location: string;
    type: string;
    result: string;
    score: string;
    evaluation: string;
    createTime: string;
};

/**
 * InterviewListReq
 */
export type InterviewListReq = {
    postId: string;
};

/**
 * InterviewListResp
 */
export type InterviewListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: Array<InterviewInfo>;
};

/**
 * InterviewUpdateResp
 */
export type InterviewUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * InterviewWithJobInfo
 */
export type InterviewWithJobInfo = {
    id: string;
    postId: string;
    round: string;
    interviewerId: string;
    interviewerName: string;
    scheduledAt: string;
    location: string;
    type: string;
    result: string;
    score: string;
    evaluation: string;
    createTime: string;
    jobId: string;
    jobTitle: string;
    companyTitle: string;
    jobLocation: string;
    categoryTitle: string;
    departmentTitle: string;
    postStatus: string;
};

/**
 * JobCategoryListResp
 */
export type JobCategoryListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: CategoryListData;
};

/**
 * JobCreateResp
 */
export type JobCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * JobDeleteResp
 */
export type JobDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * JobDetailReq
 */
export type JobDetailReq = {
    id: string;
};

/**
 * JobDetailResp
 */
export type JobDetailResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: JobInfo;
};

/**
 * JobInfo
 */
export type JobInfo = {
    id: string;
    jobCode: string;
    title: string;
    description: string;
    requirement: string;
    education: string;
    status: number;
    createTime: string;
    updateTime: string;
    location: string;
    address: string;
    minSalary: number;
    maxSalary: number;
    salaryUnit: number;
    salaryShow: string;
    workExpe: string;
    pv: number;
    category: string;
    recruitType: string;
    jobNature: string;
    departmentId: string;
    departmentTitle: string;
    companyId: string;
    companyTitle: string;
};

/**
 * JobListData
 */
export type JobListData = {
    list: Array<JobInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * JobListReq
 */
export type JobListReq = {
    keyword?: string;
    sort?: string;
    category?: string;
    recruitType?: string;
    jobNature?: string;
    salaryMin?: number;
    salaryMax?: number;
    page?: number;
    pageSize?: number;
};

/**
 * JobListResp
 */
export type JobListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: JobListData;
};

/**
 * JobUpdateResp
 */
export type JobUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * JobUserListReq
 */
export type JobUserListReq = {
    page?: number;
    pageSize?: number;
    keyword?: string;
};

/**
 * JobUserListResp
 */
export type JobUserListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: JobListData;
};

/**
 * LoginLogListReq
 */
export type LoginLogListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * LoginLogListResp
 */
export type LoginLogListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: OpLogListData;
};

/**
 * LoginReq
 */
export type LoginReq = {
    username: string;
    password: string;
};

/**
 * OfferCreateResp
 */
export type OfferCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * OfferDeleteResp
 */
export type OfferDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * OfferDetailReq
 */
export type OfferDetailReq = {
    postId: string;
};

/**
 * OfferDetailResp
 */
export type OfferDetailResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: OfferInfo;
};

/**
 * OfferInfo
 */
export type OfferInfo = {
    id: string;
    postId: string;
    salary: string;
    level: string;
    joinDate: string;
    contractPeriod: string;
    probationPeriod: string;
    workLocation: string;
    status: string;
    createTime: string;
};

/**
 * OfferListData
 */
export type OfferListData = {
    list: Array<OfferInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * OfferListReq
 */
export type OfferListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * OfferListResp
 */
export type OfferListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: OfferListData;
};

/**
 * OfferUpdateResp
 */
export type OfferUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * OfferWithJobInfo
 */
export type OfferWithJobInfo = {
    id: string;
    postId: string;
    salary: string;
    level: string;
    joinDate: string;
    contractPeriod: string;
    probationPeriod: string;
    workLocation: string;
    status: string;
    createTime: string;
    jobId: string;
    jobTitle: string;
    companyTitle: string;
    jobLocation: string;
    categoryTitle: string;
    departmentTitle: string;
    postStatus: string;
};

/**
 * OpLogInfo
 */
export type OpLogInfo = {
    id: string;
    requestId: string;
    reIp: string;
    reTime: string;
    reUa: string;
    reUrl: string;
    reMethod: string;
    reContent: string;
    success: string;
    bizCode: number;
    bizMsg: string;
    accessTime: string;
};

/**
 * OpLogListData
 */
export type OpLogListData = {
    list: Array<OpLogInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * OpLogListReq
 */
export type OpLogListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * OpLogListResp
 */
export type OpLogListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: OpLogListData;
};

/**
 * ParseResultReq
 */
export type ParseResultReq = {
    taskId: string;
};

/**
 * ParseResumeReq
 */
export type ParseResumeReq = {
    rawFile?: string;
};

/**
 * ParseResumeResult
 */
export type ParseResumeResult = {
    name: string;
    email: string;
    mobile: string;
    skills: Array<string>;
    info: string;
    rawText: string;
};

/**
 * ParseTaskInfo
 */
export type ParseTaskInfo = {
    status: string;
    result?: ParseResumeResult;
    msg?: string;
    meta?: ParseTaskMeta;
};

/**
 * ParseTaskMeta
 */
export type ParseTaskMeta = {
    fileName: string;
    textLength: number;
    llmStatus: string;
    llmError?: string;
    strategy: string;
    startedAt?: string;
    finishedAt?: string;
    extractError?: string;
};

/**
 * PostCompanyListReq
 */
export type PostCompanyListReq = {
    companyId?: string;
    page?: number;
    pageSize?: number;
};

/**
 * PostCompanyListResp
 */
export type PostCompanyListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: PostListData;
};

/**
 * PostCreateFromSnapshotResp
 */
export type PostCreateFromSnapshotResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * PostCreateResp
 */
export type PostCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * PostDeleteResp
 */
export type PostDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * PostInfo
 */
export type PostInfo = {
    id: string;
    title: string;
    companyTitle: string;
    name: string;
    resumeSnapshotId: string;
    raw: string;
    jobId: string;
    companyId: string;
    status: string;
    feedback: string;
    remark: string;
    source: string;
    userId: string;
    createTime: string;
};

/**
 * PostListData
 */
export type PostListData = {
    list: Array<PostInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * PostListReq
 */
export type PostListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * PostListResp
 */
export type PostListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: PostListData;
};

/**
 * PostStatusLogListResp
 */
export type PostStatusLogListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: Array<StatusLogInfo>;
};

/**
 * PostUpdateResp
 */
export type PostUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * PostUserInterviewListResp
 */
export type PostUserInterviewListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: Array<InterviewWithJobInfo>;
};

/**
 * PostUserListReq
 */
export type PostUserListReq = {
    userId: string;
    page?: number;
    pageSize?: number;
};

/**
 * PostUserListResp
 */
export type PostUserListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: UserPostListData;
};

/**
 * PostUserOfferListResp
 */
export type PostUserOfferListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: Array<OfferWithJobInfo>;
};

/**
 * ResumeCompanyUploadResp
 */
export type ResumeCompanyUploadResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: TaskIdData;
};

/**
 * ResumeCreateResp
 */
export type ResumeCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * ResumeDeleteResp
 */
export type ResumeDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * ResumeDetailReq
 */
export type ResumeDetailReq = {
    userId: string;
};

/**
 * ResumeDetailResp
 */
export type ResumeDetailResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: ResumeInfo;
};

/**
 * ResumeInfo
 */
export type ResumeInfo = {
    id: string;
    cover: string;
    name: string;
    sex: string;
    birthday: string;
    raw: string;
    education: string;
    school: string;
    email: string;
    mobile: string;
    summary: string;
    skills: string;
    experience: string;
    projects: string;
    eduDetail: string;
    expectedSalary: string;
    jobIntention: string;
    source: string;
    createTime: string;
    userId: string;
};

/**
 * ResumeListData
 */
export type ResumeListData = {
    list: Array<ResumeInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * ResumeListReq
 */
export type ResumeListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * ResumeListResp
 */
export type ResumeListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: ResumeListData;
};

/**
 * ResumeParseResp
 */
export type ResumeParseResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: TaskIdData;
};

/**
 * ResumeParseResultResp
 */
export type ResumeParseResultResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: ParseTaskInfo;
};

/**
 * ResumeSnapshotDeleteResp
 */
export type ResumeSnapshotDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * ResumeSnapshotDetailReq
 */
export type ResumeSnapshotDetailReq = {
    id: string;
};

/**
 * ResumeSnapshotDetailResp
 */
export type ResumeSnapshotDetailResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: ResumeSnapshotInfo;
};

/**
 * ResumeSnapshotInfo
 */
export type ResumeSnapshotInfo = {
    id: string;
    userId: string;
    resumeId: string;
    name: string;
    sex: string;
    birthday: string;
    cover: string;
    email: string;
    mobile: string;
    education: string;
    school: string;
    skills: string;
    experience: string;
    projects: string;
    summary: string;
    eduDetail: string;
    expectedSalary: string;
    jobIntention: string;
    raw: string;
    rating: number;
    tags: string;
    remark: string;
    source: string;
    createTime: string;
};

/**
 * ResumeSnapshotListData
 */
export type ResumeSnapshotListData = {
    list: Array<ResumeSnapshotInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * ResumeSnapshotListReq
 */
export type ResumeSnapshotListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * ResumeSnapshotListResp
 */
export type ResumeSnapshotListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: ResumeSnapshotListData;
};

/**
 * ResumeSnapshotStatusLogListResp
 */
export type ResumeSnapshotStatusLogListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: Array<StatusLogInfo>;
};

/**
 * ResumeSnapshotUpdateResp
 */
export type ResumeSnapshotUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * ResumeUpdateResp
 */
export type ResumeUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * StatusLogInfo
 */
export type StatusLogInfo = {
    id: string;
    targetType: string;
    targetId: string;
    fromStatus: string;
    toStatus: string;
    feedback: string;
    remark: string;
    operatorId: string;
    operatorName: string;
    createTime: number;
};

/**
 * StatusLogListReq
 */
export type StatusLogListReq = {
    targetType: string;
    targetId: string;
};

/**
 * TalentPoolAddReq
 */
export type TalentPoolAddReq = {
    resumeSnapshotId: string;
    tags?: string;
    remark?: string;
};

/**
 * TalentPoolAddResp
 */
export type TalentPoolAddResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * TalentPoolInfo
 */
export type TalentPoolInfo = {
    id: string;
    resumeSnapshotId: string;
    name: string;
    sex: string;
    email: string;
    mobile: string;
    education: string;
    school: string;
    skills: string;
    experience: string;
    projects: string;
    summary: string;
    eduDetail: string;
    expectedSalary: string;
    jobIntention: string;
    raw: string;
    source: string;
    rating: number;
    tags: string;
    remark: string;
    createTime: string;
};

/**
 * TalentPoolListData
 */
export type TalentPoolListData = {
    list: Array<TalentPoolInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * TalentPoolListReq
 */
export type TalentPoolListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * TalentPoolListResp
 */
export type TalentPoolListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: TalentPoolListData;
};

/**
 * TalentPoolRemoveReq
 */
export type TalentPoolRemoveReq = {
    resumeSnapshotId: string;
};

/**
 * TalentPoolRemoveResp
 */
export type TalentPoolRemoveResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * TalentPoolUpdateReq
 */
export type TalentPoolUpdateReq = {
    resumeSnapshotId: string;
    tags?: string;
    remark?: string;
};

/**
 * TalentPoolUpdateResp
 */
export type TalentPoolUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * TaskIdData
 */
export type TaskIdData = {
    taskId: string;
};

/**
 * UpdateCompanyReq
 */
export type UpdateCompanyReq = {
    id: string;
    title?: string;
    guimo?: string;
    hangye?: string;
    description?: string;
    location?: string;
};

/**
 * UpdateDepartmentReq
 */
export type UpdateDepartmentReq = {
    id: string;
    title?: string;
    description?: string;
    parentId?: string;
};

/**
 * UpdateInterviewReq
 */
export type UpdateInterviewReq = {
    id: string;
    interviewerId?: string;
    interviewerName?: string;
    scheduledAt?: string;
    location?: string;
    type?: string;
    result?: string;
    score?: string;
    evaluation?: string;
};

/**
 * UpdateJobReq
 */
export type UpdateJobReq = {
    id: string;
    title?: string;
    jobCode?: string;
    description?: string;
    requirement?: string;
    education?: string;
    status?: number;
    location?: string;
    address?: string;
    minSalary?: number;
    maxSalary?: number;
    salaryUnit?: number;
    salaryShow?: string;
    workExpe?: string;
    category?: string;
    recruitType?: string;
    jobNature?: string;
    departmentId?: string;
    userId?: string;
    companyId?: string;
};

/**
 * UpdateOfferReq
 */
export type UpdateOfferReq = {
    id: string;
    salary?: string;
    level?: string;
    joinDate?: string;
    contractPeriod?: string;
    probationPeriod?: string;
    workLocation?: string;
    status?: string;
};

/**
 * UpdatePostReq
 */
export type UpdatePostReq = {
    id: string;
    resumeSnapshotId?: string;
    jobId?: string;
    companyId?: string;
    status?: string;
    feedback?: string;
    remark?: string;
    source?: string;
};

/**
 * UpdatePwdReq
 */
export type UpdatePwdReq = {
    userId: string;
    oldPassword: string;
    newPassword: string;
};

/**
 * UpdateResumeReq
 */
export type UpdateResumeReq = {
    id: string;
    cover?: string;
    name?: string;
    sex?: string;
    birthday?: string;
    raw?: string;
    education?: string;
    school?: string;
    email?: string;
    mobile?: string;
    userId: string;
    summary?: string;
    skills?: string;
    experience?: string;
    projects?: string;
    eduDetail?: string;
    expectedSalary?: string;
    jobIntention?: string;
    source?: string;
    coverFile?: string;
    rawFile?: string;
};

/**
 * UpdateResumeSnapshotReq
 */
export type UpdateResumeSnapshotReq = {
    id: string;
    name?: string;
    sex?: string;
    email?: string;
    mobile?: string;
    education?: string;
    school?: string;
    summary?: string;
    skills?: string;
    experience?: string;
    projects?: string;
    eduDetail?: string;
    expectedSalary?: string;
    jobIntention?: string;
    rating?: string;
    tags?: string;
    remark?: string;
    source?: string;
};

/**
 * UpdateUserInfoReq
 */
export type UpdateUserInfoReq = {
    id: string;
    nickname?: string;
    mobile?: string;
    email?: string;
    pushEmail?: string;
    pushSwitch?: string;
};

/**
 * UpdateUserReq
 */
export type UpdateUserReq = {
    id: string;
    username?: string;
    password?: string;
    nickname?: string;
    mobile?: string;
    email?: string;
    role?: string;
    status?: string;
    pushEmail?: string;
    pushSwitch?: string;
};

/**
 * UserCreateResp
 */
export type UserCreateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * UserDeleteResp
 */
export type UserDeleteResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * UserDetailReq
 */
export type UserDetailReq = {
    userId: string;
};

/**
 * UserDetailResp
 */
export type UserDetailResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: UserInfo;
};

/**
 * UserInfo
 */
export type UserInfo = {
    id: string;
    username: string;
    password: string;
    nickname: string;
    mobile: string;
    email: string;
    role: string;
    status: string;
    token: string;
    createTime: string;
    pushEmail: string;
    pushSwitch: string;
    avatar?: string;
};

/**
 * UserInterviewListReq
 */
export type UserInterviewListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * UserListData
 */
export type UserListData = {
    list: Array<UserInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * UserListReq
 */
export type UserListReq = {
    keyword?: string;
    page?: number;
    pageSize?: number;
};

/**
 * UserListResp
 */
export type UserListResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: UserListData;
};

/**
 * UserLoginReq
 */
export type UserLoginReq = {
    username: string;
    password: string;
};

/**
 * UserLoginResp
 */
export type UserLoginResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: UserInfo;
};

/**
 * UserLoginResp2
 */
export type UserLoginResp2 = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
    data?: UserInfo;
};

/**
 * UserOfferListReq
 */
export type UserOfferListReq = {
    page?: number;
    pageSize?: number;
};

/**
 * UserPostItemInfo
 */
export type UserPostItemInfo = {
    id: string;
    jobId: string;
    title: string;
    status: string;
    feedback: string;
    source: string;
    companyTitle: string;
    location: string;
    categoryTitle: string;
    departmentTitle: string;
};

/**
 * UserPostListData
 */
export type UserPostListData = {
    list: Array<UserPostItemInfo>;
    total: number;
    page: number;
    pageSize: number;
};

/**
 * UserRegisterReq
 */
export type UserRegisterReq = {
    username: string;
    password: string;
    rePassword: string;
    nickname?: string;
    mobile?: string;
    email?: string;
};

/**
 * UserRegisterResp
 */
export type UserRegisterResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * UserUpdatePwdResp
 */
export type UserUpdatePwdResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * UserUpdateResp
 */
export type UserUpdateResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

/**
 * UserUpdateUserInfoResp
 */
export type UserUpdateUserInfoResp = {
    code?: number;
    msg?: string;
    trace?: string;
    timestamp?: number;
};

export type CompanyCreateData = {
    body: CreateCompanyReq;
    path?: never;
    query?: never;
    url: '/api/company/create';
};

export type CompanyCreateResponses = {
    /**
     * A successful response.
     */
    200: CompanyCreateResp;
};

export type CompanyCreateResponse = CompanyCreateResponses[keyof CompanyCreateResponses];

export type CompanyDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/company/delete';
};

export type CompanyDeleteResponses = {
    /**
     * A successful response.
     */
    200: CompanyDeleteResp;
};

export type CompanyDeleteResponse = CompanyDeleteResponses[keyof CompanyDeleteResponses];

export type CompanyListData2 = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/company/list';
};

export type CompanyListResponses = {
    /**
     * A successful response.
     */
    200: CompanyListResp;
};

export type CompanyListResponse = CompanyListResponses[keyof CompanyListResponses];

export type CompanyUpdateData = {
    body: UpdateCompanyReq;
    path?: never;
    query?: never;
    url: '/api/company/update';
};

export type CompanyUpdateResponses = {
    /**
     * A successful response.
     */
    200: CompanyUpdateResp;
};

export type CompanyUpdateResponse = CompanyUpdateResponses[keyof CompanyUpdateResponses];

export type DepartmentCreateData = {
    body: CreateDepartmentReq;
    path?: never;
    query?: never;
    url: '/api/department/create';
};

export type DepartmentCreateResponses = {
    /**
     * A successful response.
     */
    200: DepartmentCreateResp;
};

export type DepartmentCreateResponse = DepartmentCreateResponses[keyof DepartmentCreateResponses];

export type DepartmentDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/department/delete';
};

export type DepartmentDeleteResponses = {
    /**
     * A successful response.
     */
    200: DepartmentDeleteResp;
};

export type DepartmentDeleteResponse = DepartmentDeleteResponses[keyof DepartmentDeleteResponses];

export type DepartmentListData2 = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/department/list';
};

export type DepartmentListResponses = {
    /**
     * A successful response.
     */
    200: DepartmentListResp;
};

export type DepartmentListResponse = DepartmentListResponses[keyof DepartmentListResponses];

export type DepartmentUpdateData = {
    body: UpdateDepartmentReq;
    path?: never;
    query?: never;
    url: '/api/department/update';
};

export type DepartmentUpdateResponses = {
    /**
     * A successful response.
     */
    200: DepartmentUpdateResp;
};

export type DepartmentUpdateResponse = DepartmentUpdateResponses[keyof DepartmentUpdateResponses];

export type InterviewCreateData = {
    body: CreateInterviewReq;
    path?: never;
    query?: never;
    url: '/api/interview/create';
};

export type InterviewCreateResponses = {
    /**
     * A successful response.
     */
    200: InterviewCreateResp;
};

export type InterviewCreateResponse = InterviewCreateResponses[keyof InterviewCreateResponses];

export type InterviewListData = {
    body?: never;
    path?: never;
    query: {
        postId: string;
    };
    url: '/api/interview/list';
};

export type InterviewListResponses = {
    /**
     * A successful response.
     */
    200: InterviewListResp;
};

export type InterviewListResponse = InterviewListResponses[keyof InterviewListResponses];

export type InterviewUpdateData = {
    body: UpdateInterviewReq;
    path?: never;
    query?: never;
    url: '/api/interview/update';
};

export type InterviewUpdateResponses = {
    /**
     * A successful response.
     */
    200: InterviewUpdateResp;
};

export type InterviewUpdateResponse = InterviewUpdateResponses[keyof InterviewUpdateResponses];

export type JobCategoryListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/job/categoryList';
};

export type JobCategoryListResponses = {
    /**
     * A successful response.
     */
    200: JobCategoryListResp;
};

export type JobCategoryListResponse = JobCategoryListResponses[keyof JobCategoryListResponses];

export type JobCreateData = {
    body: CreateJobReq;
    path?: never;
    query?: never;
    url: '/api/job/create';
};

export type JobCreateResponses = {
    /**
     * A successful response.
     */
    200: JobCreateResp;
};

export type JobCreateResponse = JobCreateResponses[keyof JobCreateResponses];

export type JobDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/job/delete';
};

export type JobDeleteResponses = {
    /**
     * A successful response.
     */
    200: JobDeleteResp;
};

export type JobDeleteResponse = JobDeleteResponses[keyof JobDeleteResponses];

export type JobDetailData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/api/job/detail';
};

export type JobDetailResponses = {
    /**
     * A successful response.
     */
    200: JobDetailResp;
};

export type JobDetailResponse = JobDetailResponses[keyof JobDetailResponses];

export type JobListData2 = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        sort?: string;
        category?: string;
        recruitType?: string;
        jobNature?: string;
        salaryMin?: number;
        salaryMax?: number;
        page?: number;
        pageSize?: number;
    };
    url: '/api/job/list';
};

export type JobListResponses = {
    /**
     * A successful response.
     */
    200: JobListResp;
};

export type JobListResponse = JobListResponses[keyof JobListResponses];

export type JobUserListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        keyword?: string;
    };
    url: '/api/job/listUserJobApi';
};

export type JobUserListResponses = {
    /**
     * A successful response.
     */
    200: JobUserListResp;
};

export type JobUserListResponse = JobUserListResponses[keyof JobUserListResponses];

export type JobUpdateData = {
    body: UpdateJobReq;
    path?: never;
    query?: never;
    url: '/api/job/update';
};

export type JobUpdateResponses = {
    /**
     * A successful response.
     */
    200: JobUpdateResp;
};

export type JobUpdateResponse = JobUpdateResponses[keyof JobUpdateResponses];

export type OfferCreateData = {
    body: CreateOfferReq;
    path?: never;
    query?: never;
    url: '/api/offer/create';
};

export type OfferCreateResponses = {
    /**
     * A successful response.
     */
    200: OfferCreateResp;
};

export type OfferCreateResponse = OfferCreateResponses[keyof OfferCreateResponses];

export type OfferDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/offer/delete';
};

export type OfferDeleteResponses = {
    /**
     * A successful response.
     */
    200: OfferDeleteResp;
};

export type OfferDeleteResponse = OfferDeleteResponses[keyof OfferDeleteResponses];

export type OfferDetailData = {
    body?: never;
    path?: never;
    query: {
        postId: string;
    };
    url: '/api/offer/detail';
};

export type OfferDetailResponses = {
    /**
     * A successful response.
     */
    200: OfferDetailResp;
};

export type OfferDetailResponse = OfferDetailResponses[keyof OfferDetailResponses];

export type OfferListData2 = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/offer/list';
};

export type OfferListResponses = {
    /**
     * A successful response.
     */
    200: OfferListResp;
};

export type OfferListResponse = OfferListResponses[keyof OfferListResponses];

export type OfferUpdateData = {
    body: UpdateOfferReq;
    path?: never;
    query?: never;
    url: '/api/offer/update';
};

export type OfferUpdateResponses = {
    /**
     * A successful response.
     */
    200: OfferUpdateResp;
};

export type OfferUpdateResponse = OfferUpdateResponses[keyof OfferUpdateResponses];

export type OpLogListData2 = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/opLog/list';
};

export type OpLogListResponses = {
    /**
     * A successful response.
     */
    200: OpLogListResp;
};

export type OpLogListResponse = OpLogListResponses[keyof OpLogListResponses];

export type LoginLogListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/opLog/loginLogList';
};

export type LoginLogListResponses = {
    /**
     * A successful response.
     */
    200: LoginLogListResp;
};

export type LoginLogListResponse = LoginLogListResponses[keyof LoginLogListResponses];

export type PostCreateData = {
    body: CreatePostReq;
    path?: never;
    query?: never;
    url: '/api/post/create';
};

export type PostCreateResponses = {
    /**
     * A successful response.
     */
    200: PostCreateResp;
};

export type PostCreateResponse = PostCreateResponses[keyof PostCreateResponses];

export type PostCreateFromSnapshotData = {
    body: CreatePostFromSnapshotReq;
    path?: never;
    query?: never;
    url: '/api/post/createFromSnapshot';
};

export type PostCreateFromSnapshotResponses = {
    /**
     * A successful response.
     */
    200: PostCreateFromSnapshotResp;
};

export type PostCreateFromSnapshotResponse = PostCreateFromSnapshotResponses[keyof PostCreateFromSnapshotResponses];

export type PostDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/post/delete';
};

export type PostDeleteResponses = {
    /**
     * A successful response.
     */
    200: PostDeleteResp;
};

export type PostDeleteResponse = PostDeleteResponses[keyof PostDeleteResponses];

export type PostListData2 = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/list';
};

export type PostListResponses = {
    /**
     * A successful response.
     */
    200: PostListResp;
};

export type PostListResponse = PostListResponses[keyof PostListResponses];

export type PostCompanyListData = {
    body?: never;
    path?: never;
    query?: {
        companyId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/listCompanyPostApi';
};

export type PostCompanyListResponses = {
    /**
     * A successful response.
     */
    200: PostCompanyListResp;
};

export type PostCompanyListResponse = PostCompanyListResponses[keyof PostCompanyListResponses];

export type PostUserListData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/listUserPostApi';
};

export type PostUserListResponses = {
    /**
     * A successful response.
     */
    200: PostUserListResp;
};

export type PostUserListResponse = PostUserListResponses[keyof PostUserListResponses];

export type PostStatusLogListData = {
    body?: never;
    path?: never;
    query: {
        targetType: string;
        targetId: string;
    };
    url: '/api/post/statusLogList';
};

export type PostStatusLogListResponses = {
    /**
     * A successful response.
     */
    200: PostStatusLogListResp;
};

export type PostStatusLogListResponse = PostStatusLogListResponses[keyof PostStatusLogListResponses];

export type PostUpdateData = {
    body: UpdatePostReq;
    path?: never;
    query?: never;
    url: '/api/post/update';
};

export type PostUpdateResponses = {
    /**
     * A successful response.
     */
    200: PostUpdateResp;
};

export type PostUpdateResponse = PostUpdateResponses[keyof PostUpdateResponses];

export type PostUserInterviewListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/userInterviewList';
};

export type PostUserInterviewListResponses = {
    /**
     * A successful response.
     */
    200: PostUserInterviewListResp;
};

export type PostUserInterviewListResponse = PostUserInterviewListResponses[keyof PostUserInterviewListResponses];

export type PostUserOfferListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/post/userOfferList';
};

export type PostUserOfferListResponses = {
    /**
     * A successful response.
     */
    200: PostUserOfferListResp;
};

export type PostUserOfferListResponse = PostUserOfferListResponses[keyof PostUserOfferListResponses];

export type ResumeCompanyUploadData = {
    body: CompanyUploadResumeReq;
    path?: never;
    query?: never;
    url: '/api/resume/companyUpload';
};

export type ResumeCompanyUploadResponses = {
    /**
     * A successful response.
     */
    200: ResumeCompanyUploadResp;
};

export type ResumeCompanyUploadResponse = ResumeCompanyUploadResponses[keyof ResumeCompanyUploadResponses];

export type ResumeCreateData = {
    body: CreateResumeReq;
    path?: never;
    query?: never;
    url: '/api/resume/create';
};

export type ResumeCreateResponses = {
    /**
     * A successful response.
     */
    200: ResumeCreateResp;
};

export type ResumeCreateResponse = ResumeCreateResponses[keyof ResumeCreateResponses];

export type ResumeDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/resume/delete';
};

export type ResumeDeleteResponses = {
    /**
     * A successful response.
     */
    200: ResumeDeleteResp;
};

export type ResumeDeleteResponse = ResumeDeleteResponses[keyof ResumeDeleteResponses];

export type ResumeDetailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
    };
    url: '/api/resume/detail';
};

export type ResumeDetailResponses = {
    /**
     * A successful response.
     */
    200: ResumeDetailResp;
};

export type ResumeDetailResponse = ResumeDetailResponses[keyof ResumeDetailResponses];

export type ResumeListData2 = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/resume/list';
};

export type ResumeListResponses = {
    /**
     * A successful response.
     */
    200: ResumeListResp;
};

export type ResumeListResponse = ResumeListResponses[keyof ResumeListResponses];

export type ResumeParseData = {
    body: ParseResumeReq;
    path?: never;
    query?: never;
    url: '/api/resume/parse';
};

export type ResumeParseResponses = {
    /**
     * A successful response.
     */
    200: ResumeParseResp;
};

export type ResumeParseResponse = ResumeParseResponses[keyof ResumeParseResponses];

export type ResumeParseResultData = {
    body?: never;
    path?: never;
    query: {
        taskId: string;
    };
    url: '/api/resume/parseResult';
};

export type ResumeParseResultResponses = {
    /**
     * A successful response.
     */
    200: ResumeParseResultResp;
};

export type ResumeParseResultResponse = ResumeParseResultResponses[keyof ResumeParseResultResponses];

export type ResumeUpdateData = {
    body: UpdateResumeReq;
    path?: never;
    query?: never;
    url: '/api/resume/update';
};

export type ResumeUpdateResponses = {
    /**
     * A successful response.
     */
    200: ResumeUpdateResp;
};

export type ResumeUpdateResponse = ResumeUpdateResponses[keyof ResumeUpdateResponses];

export type ResumeSnapshotDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/resumeSnapshot/delete';
};

export type ResumeSnapshotDeleteResponses = {
    /**
     * A successful response.
     */
    200: ResumeSnapshotDeleteResp;
};

export type ResumeSnapshotDeleteResponse = ResumeSnapshotDeleteResponses[keyof ResumeSnapshotDeleteResponses];

export type ResumeSnapshotDetailData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/api/resumeSnapshot/detail';
};

export type ResumeSnapshotDetailResponses = {
    /**
     * A successful response.
     */
    200: ResumeSnapshotDetailResp;
};

export type ResumeSnapshotDetailResponse = ResumeSnapshotDetailResponses[keyof ResumeSnapshotDetailResponses];

export type ResumeSnapshotListData2 = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/resumeSnapshot/list';
};

export type ResumeSnapshotListResponses = {
    /**
     * A successful response.
     */
    200: ResumeSnapshotListResp;
};

export type ResumeSnapshotListResponse = ResumeSnapshotListResponses[keyof ResumeSnapshotListResponses];

export type ResumeSnapshotStatusLogListData = {
    body?: never;
    path?: never;
    query: {
        targetType: string;
        targetId: string;
    };
    url: '/api/resumeSnapshot/statusLogList';
};

export type ResumeSnapshotStatusLogListResponses = {
    /**
     * A successful response.
     */
    200: ResumeSnapshotStatusLogListResp;
};

export type ResumeSnapshotStatusLogListResponse = ResumeSnapshotStatusLogListResponses[keyof ResumeSnapshotStatusLogListResponses];

export type ResumeSnapshotUpdateData = {
    body: UpdateResumeSnapshotReq;
    path?: never;
    query?: never;
    url: '/api/resumeSnapshot/update';
};

export type ResumeSnapshotUpdateResponses = {
    /**
     * A successful response.
     */
    200: ResumeSnapshotUpdateResp;
};

export type ResumeSnapshotUpdateResponse = ResumeSnapshotUpdateResponses[keyof ResumeSnapshotUpdateResponses];

export type TalentPoolAddData = {
    body: TalentPoolAddReq;
    path?: never;
    query?: never;
    url: '/api/talentPool/add';
};

export type TalentPoolAddResponses = {
    /**
     * A successful response.
     */
    200: TalentPoolAddResp;
};

export type TalentPoolAddResponse = TalentPoolAddResponses[keyof TalentPoolAddResponses];

export type TalentPoolListData2 = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/talentPool/list';
};

export type TalentPoolListResponses = {
    /**
     * A successful response.
     */
    200: TalentPoolListResp;
};

export type TalentPoolListResponse = TalentPoolListResponses[keyof TalentPoolListResponses];

export type TalentPoolRemoveData = {
    body: TalentPoolRemoveReq;
    path?: never;
    query?: never;
    url: '/api/talentPool/remove';
};

export type TalentPoolRemoveResponses = {
    /**
     * A successful response.
     */
    200: TalentPoolRemoveResp;
};

export type TalentPoolRemoveResponse = TalentPoolRemoveResponses[keyof TalentPoolRemoveResponses];

export type TalentPoolUpdateData = {
    body: TalentPoolUpdateReq;
    path?: never;
    query?: never;
    url: '/api/talentPool/update';
};

export type TalentPoolUpdateResponses = {
    /**
     * A successful response.
     */
    200: TalentPoolUpdateResp;
};

export type TalentPoolUpdateResponse = TalentPoolUpdateResponses[keyof TalentPoolUpdateResponses];

export type UserCreateData = {
    body: CreateUserReq;
    path?: never;
    query?: never;
    url: '/api/user/create';
};

export type UserCreateResponses = {
    /**
     * A successful response.
     */
    200: UserCreateResp;
};

export type UserCreateResponse = UserCreateResponses[keyof UserCreateResponses];

export type UserDeleteData = {
    body: DeleteReq;
    path?: never;
    query?: never;
    url: '/api/user/delete';
};

export type UserDeleteResponses = {
    /**
     * A successful response.
     */
    200: UserDeleteResp;
};

export type UserDeleteResponse = UserDeleteResponses[keyof UserDeleteResponses];

export type UserDetailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
    };
    url: '/api/user/detail';
};

export type UserDetailResponses = {
    /**
     * A successful response.
     */
    200: UserDetailResp;
};

export type UserDetailResponse = UserDetailResponses[keyof UserDetailResponses];

export type UserListData2 = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/user/list';
};

export type UserListResponses = {
    /**
     * A successful response.
     */
    200: UserListResp;
};

export type UserListResponse = UserListResponses[keyof UserListResponses];

export type UserLoginData = {
    body: LoginReq;
    path?: never;
    query?: never;
    url: '/api/user/login';
};

export type UserLoginResponses = {
    /**
     * A successful response.
     */
    200: UserLoginResp;
};

export type UserLoginResponse = UserLoginResponses[keyof UserLoginResponses];

export type UserUpdateData = {
    body: UpdateUserReq;
    path?: never;
    query?: never;
    url: '/api/user/update';
};

export type UserUpdateResponses = {
    /**
     * A successful response.
     */
    200: UserUpdateResp;
};

export type UserUpdateResponse = UserUpdateResponses[keyof UserUpdateResponses];

export type UserUpdatePwdData = {
    body: UpdatePwdReq;
    path?: never;
    query?: never;
    url: '/api/user/updatePwd';
};

export type UserUpdatePwdResponses = {
    /**
     * A successful response.
     */
    200: UserUpdatePwdResp;
};

export type UserUpdatePwdResponse = UserUpdatePwdResponses[keyof UserUpdatePwdResponses];

export type UserUpdateUserInfoData = {
    body: UpdateUserInfoReq;
    path?: never;
    query?: never;
    url: '/api/user/updateUserInfo';
};

export type UserUpdateUserInfoResponses = {
    /**
     * A successful response.
     */
    200: UserUpdateUserInfoResp;
};

export type UserUpdateUserInfoResponse = UserUpdateUserInfoResponses[keyof UserUpdateUserInfoResponses];

export type UserUserLoginData = {
    body: UserLoginReq;
    path?: never;
    query?: never;
    url: '/api/user/userLogin';
};

export type UserUserLoginResponses = {
    /**
     * A successful response.
     */
    200: UserLoginResp2;
};

export type UserUserLoginResponse = UserUserLoginResponses[keyof UserUserLoginResponses];

export type UserRegisterData = {
    body: UserRegisterReq;
    path?: never;
    query?: never;
    url: '/api/user/userRegister';
};

export type UserRegisterResponses = {
    /**
     * A successful response.
     */
    200: UserRegisterResp;
};

export type UserRegisterResponse = UserRegisterResponses[keyof UserRegisterResponses];
